openapi: 3.1.0
info:
  title: Change password
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /auth/v1/mfa/password/change:
    post:
      summary: Change password
      description: API to change the password.
      operationId: change-mfa-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - deviceId
              - password
              - newPassword
              - confirmPassword
              - brand
              - token
              - identifierType
              - identifierValue
              properties:
                deviceId:
                  type: string
                  description: Unique ID of the device used for password validation.
                    It should be the same device used to generate the MFA token.
                password:
                  type: string
                  description: Current password.
                newPassword:
                  type: string
                  description: New password.
                confirmPassword:
                  type: string
                  description: Re-enter the new password.
                brand:
                  type: string
                  description: Name of the brand or organisation that needs verification.
                token:
                  type: string
                  description: Token generated from `/mfa/password/validate` .
                identifierType:
                  type: string
                  description: The type of identifier to identify the customer.
                  enum:
                  - MOBILE
                  - EMAIL
                  - USERNAME
                  - EXTERNALID
                identifierValue:
                  type: string
                  description: Value of the identifier.
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 200,\n        \"message\": \"SUCCESS\"\n    }\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: SUCCESS
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
