openapi: 3.1.0
info:
  title: Change Password
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /auth/v1/password/change:
    post:
      summary: Change Password
      description: Lets you modify the current password of a customer. This is applicable
        only for brands for which password is enabled.
      operationId: change-password-1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - identifierType
              - identifierValue
              - brand
              - deviceId
              - password
              - newPassword
              - confirmPassword
              - token
              properties:
                identifierType:
                  type: string
                  description: "Identifier used for token generation. Values: MOBILE,\
                    \ EMAIL, USERNAME."
                identifierValue:
                  type: string
                  description: Value of the specified identifierType.
                brand:
                  type: string
                  description: Name of the brand/org for which authentication needs
                    to be verified.
                deviceId:
                  type: string
                  description: Unique ID of the device used for changing password.
                    Applicable only for mobile app.
                password:
                  type: string
                  description: Current password of the account.
                newPassword:
                  type: string
                  description: New password of the account.
                confirmPassword:
                  type: string
                  description: Reenter the new password.
                token:
                  type: string
                  description: Unique token generated for the identifierType, identifierValue
                    and for web application, and including deviceId for the mobile
                    application.
            examples:
              Sample POST Body:
                value:
                  identifierType: USERNAME
                  identifierValue: '9940000000'
                  deviceId: deviceid1
                  brand: KANMODEMO
                  password: password
                  newPassword: password1
                  confirmPassword: password1
                  token: eyJpZHYiOlsiTU9CSUxFfDk5NDU1NjAyMjQiLCJVU0VSTkFNRXw5OTQ1NTYwMjI0Il0sImRldiI6ImRldmljZWlkMSIsIm9yZyI6IlNUQU5EQVJEQVBQIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjE1MTA2MHxzYS5kZW1vLnNvbHV0aW9uIl0sImV4cCI6MTU5Nzg0MzczMywiaWF0IjoxNTk3ODQwMTMzLCJyb2wiOiJWSUVXIn0.pKYy3FpZm82igqp5CRUku4WF8pT5JEp6mX3P48M2qvY
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 200,\n        \"message\": \"SUCCESS\"\n    }\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: SUCCESS
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
