openapi: 3.1.0
info:
  title: Enrol customers for badges
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/badgeMeta/customer/issueBulk:
    post:
      summary: Enrol customers for badges
      description: ''
      operationId: enrol-customers-for-badges
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - badgeMetaId
              properties:
                badgeMetaId:
                  type: string
                  description: Unique meta ID of the badge.
                customers:
                  type: object
                  properties: {}
                requestId:
                  type: string
                triggeredBy:
                  type: object
                  properties: {}
                issueEventDate:
                  type: string
                  description: "The date on which customer was enrolled in the badge.\
                    \ Issue event date has to be between the badge start date and\
                    \ end date. Timestamp in the ISO 8601 standard format format YYYY-MM-DDTHH:MM:SS.SSSZ."
                  format: date-time
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response for single customer:
                  value:
                    data:
                      badgeMetaId: 69807855eba595729385eb1b
                      triggeredBy:
                        ownerType: Rewards_Catalog
                        referenceId: '123'
                      expiresOn: 1926235957
                      expiresOnISO: "2031-01-15T09:32:37Z"
                      issuedBadges:
                      - customerId: 566135941
                        issuedId: 69807865eba595729385eb1c
                        status: ACTIVE
                      requestId: req12
                    errors: []
                    warnings: []
                  summary: Sample response for single customer
                Sample response for multiple customers:
                  value:
                    data:
                      badgeMetaId: 6980795d0772ad476ed02639
                      triggeredBy:
                        ownerType: Rewards_Catalog
                        referenceId: '123'
                      expiresOn: 1926235957
                      expiresOnISO: "2031-01-15T09:32:37Z"
                      issuedBadges:
                      - customerId: 566135941
                        issuedId: 69807969eba595729385eb28
                        status: ACTIVE
                      - customerId: 565039506
                        issuedId: 69807969eba595729385eb29
                        status: ACTIVE
                      requestId: req14
                    errors: []
                    warnings: []
                  summary: Sample response for multiple customers
              schema:
                oneOf:
                - title: Single customer
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 66276dc68fe258516a88ff8e
                        triggeredBy:
                          type: object
                          properties:
                            ownerType:
                              type: string
                              example: Loyalty
                            referenceId:
                              type: string
                              example: '123694'
                        expiresOn:
                          type: integer
                          example: 1926235957
                          default: 0
                        issuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 62090013
                                default: 0
                              issuedId:
                                type: string
                                example: 66276df28fe258516a88ff8f
                              error: {}
                        requestId:
                          type: string
                          example: '21390'
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: Multiple customers
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 653de84db3cda7078c7c68ed
                        triggeredBy:
                          type: object
                          properties:
                            ownerType:
                              type: string
                              example: Loyalty
                            referenceId:
                              type: string
                              example: '626'
                        expiresOn:
                          type: number
                          example: 1702120189.4079
                          default: 0
                        issuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 123
                                default: 0
                              issuedId:
                                type: string
                                example: 654cbdfd6bccde1274b6d3a0
                              error: {}
                        requestId:
                          type: string
                          example: 10few789
                    errors:
                      type: array
                    warnings:
                      type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"data\": null,\n    \"errors\": [\n        {\n \
                    \           \"code\": 809,\n            \"message\": \"Request\
                    \ with same requestId is not allowed\",\n            \"reference\"\
                    : null\n        }\n    ],\n    \"warnings\": null\n}"
              schema:
                type: object
                properties:
                  data: {}
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 809
                          default: 0
                        message:
                          type: string
                          example: Request with same requestId is not allowed
                        reference: {}
                  warnings: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/badgeMeta/customer/issueBulk'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization:\
            \ Basic Z2VvcmdlLmRvY2RlbW86NjVhMDgzYjk1MWY5MGY1NTY5NDk1YmNkNzUxYmJiY2U='\
            \ \\\n--header 'Cookie: _cfuvid=60YlXkyLfDaY1gOO1YdxKbhVquLZtaBlNd58D9_8rpU-1765282802951-0.0.1.1-604800000'\
            \ \\\n--data '{\n   \"badgeMetaId\": \"693804d8cebb9648d8974489\",\n \
            \  \"triggeredBy\": {\n       \"ownerType\": \"Loyalty\",\n       \"referenceId\"\
            : \"string\"\n   },\n   \"issueEventDate\": \"2025-11-03T21:51:00.192Z\"\
            ,\n   \"issueEventDateISO\": \"2025-04-23T08:14:15Z\", \n   \"customers\"\
            : [\n       566881933],\n   \"requestId\": \"434e0d861777711w2yyybj265\"\
            \n}'"
          name: Sample request for single customer
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/badgeMeta/customer/issueBulk'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization:\
            \ Basic Z2VvcmdlLmRvY2RlbW86NjVhMDgzYjk1MWY5MGY1NTY5NDk1YmNkNzUxYmJiY2U='\
            \ \\\n--header 'Cookie: _cfuvid=60YlXkyLfDaY1gOO1YdxKbhVquLZtaBlNd58D9_8rpU-1765282802951-0.0.1.1-604800000'\
            \ \\\n--data '{\n   \"badgeMetaId\": \"693804d8cebb9648d8974489\",\n \
            \  \"triggeredBy\": {\n       \"ownerType\": \"Loyalty\",\n       \"referenceId\"\
            : \"string\"\n   },\n   \"issueEventDate\": \"2025-11-03T21:51:00.192Z\"\
            ,\n   \"issueEventDateISO\": \"2025-04-23T08:14:15Z\", \n   \"customers\"\
            : [\n       566881933,\n       566881934\n   ],\n   \"requestId\": \"\
            434e0d861777711w2yyybj265\"\n}'"
          name: Sample request for multiple customers
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
