openapi: 3.1.0
info:
  title: Get fixed window details
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/badgeMeta/getFixedWindowDetails:
    get:
      summary: Get fixed window details
      description: ''
      operationId: get-fixed-window-details
      parameters:
      - name: badgeMetaId
        in: query
        required: true
        schema:
          type: string
      - name: constraintType
        in: query
        schema:
          type: string
      - name: customerId
        in: query
        schema:
          type: string
      - name: fixedWindowCycleReferenceId
        in: query
        schema:
          type: string
      - name: includeEarnCount
        in: query
        schema:
          type: string
      - name: startDate
        in: query
        schema:
          type: string
      - name: endDate
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: size
        in: query
        schema:
          type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                when includeEarnCount=true and constraintType=ALL:
                  value: "{\n    \"data\": {\n        \"badgeMetaId\": \"6603ed23e4165a7993354a76\"\
                    ,\n        \"orgId\": 4000106,\n        \"startDate\": 1709337637.192000000,\n\
                    \        \"endDate\": 1709510437.192000000,\n        \"customerId\"\
                    : 123,\n        \"fixedWindowCycles\": [\n            {\n    \
                    \            \"fixedWindowCycleReferenceId\": \"a1350b49-eb8e-3500-9e43-01f5493c91c1\"\
                    ,\n                \"startDate\": 1709337600.000000000,\n    \
                    \            \"endDate\": 1709510400.000000000,\n            \
                    \    \"earnCount\": 0,\n                \"constraintType\": \"\
                    BADGE_FIXED_WINDOW\"\n            }\n        ],\n        \"pagination\"\
                    : {\n            \"page\": 0,\n            \"size\": 30,\n   \
                    \         \"total\": 1,\n            \"totalPages\": 1\n     \
                    \   }\n    },\n    \"errors\": [],\n    \"warnings\": []\n}"
                Sample response:
                  value:
                    data:
                      badgeMetaId: 69381220cebb9648d8974518
                      orgId: 100737
                      startDate: 1740960000
                      startDateISO: "2025-03-03T00:00:00Z"
                      endDate: 1797738400
                      endDateISO: "2026-12-20T03:46:40Z"
                      fixedWindowCycles:
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1740960000
                        startDateISO: "2025-03-03T00:00:00Z"
                        endDate: 1741132800
                        endDateISO: "2025-03-05T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1741219200
                        startDateISO: "2025-03-06T00:00:00Z"
                        endDate: 1741392000
                        endDateISO: "2025-03-08T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1741478400
                        startDateISO: "2025-03-09T00:00:00Z"
                        endDate: 1741651200
                        endDateISO: "2025-03-11T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1741737600
                        startDateISO: "2025-03-12T00:00:00Z"
                        endDate: 1741910400
                        endDateISO: "2025-03-14T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1741996800
                        startDateISO: "2025-03-15T00:00:00Z"
                        endDate: 1742169600
                        endDateISO: "2025-03-17T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1742256000
                        startDateISO: "2025-03-18T00:00:00Z"
                        endDate: 1742428800
                        endDateISO: "2025-03-20T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1742515200
                        startDateISO: "2025-03-21T00:00:00Z"
                        endDate: 1742688000
                        endDateISO: "2025-03-23T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1742774400
                        startDateISO: "2025-03-24T00:00:00Z"
                        endDate: 1742947200
                        endDateISO: "2025-03-26T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1743033600
                        startDateISO: "2025-03-27T00:00:00Z"
                        endDate: 1743206400
                        endDateISO: "2025-03-29T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      - fixedWindowCycleReferenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                        startDate: 1743292800
                        startDateISO: "2025-03-30T00:00:00Z"
                        endDate: 1743465600
                        endDateISO: "2025-04-01T00:00:00Z"
                        constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                      pagination:
                        page: 0
                        size: 10
                        total: 220
                        totalPages: 22
                    errors: []
                    warnings: []
                  summary: Sample response
              schema:
                oneOf:
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 6603ed23e4165a7993354a76
                        orgId:
                          type: integer
                          example: 4000106
                          default: 0
                        startDate:
                          type: number
                          example: 1709337637.192
                          default: 0
                        endDate:
                          type: number
                          example: 1709510437.192
                          default: 0
                        customerId:
                          type: integer
                          example: 38144111
                          default: 0
                        fixedWindowCycles:
                          type: array
                          items:
                            type: object
                            properties:
                              fixedWindowCycleReferenceId:
                                type: string
                                example: a1350b49-eb8e-3500-9e43-01f5493c91c1
                              startDate:
                                type: integer
                                example: 1709337600
                                default: 0
                              endDate:
                                type: integer
                                example: 1709510400
                                default: 0
                              earnCount:
                                type: integer
                                example: 0
                                default: 0
                              constraintType:
                                type: string
                                example: BADGE_FIXED_WINDOW
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 0
                              default: 0
                            size:
                              type: integer
                              example: 30
                              default: 0
                            total:
                              type: integer
                              example: 1
                              default: 0
                            totalPages:
                              type: integer
                              example: 1
                              default: 0
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: when includeEarnCount=true and constraintType=ALL
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 6603ed23e4165a7993354a76
                        orgId:
                          type: integer
                          example: 4000106
                          default: 0
                        startDate:
                          type: number
                          example: 1709337637.192
                          default: 0
                        endDate:
                          type: number
                          example: 1709510437.192
                          default: 0
                        customerId:
                          type: integer
                          example: 123
                          default: 0
                        fixedWindowCycles:
                          type: array
                          items:
                            type: object
                            properties:
                              fixedWindowCycleReferenceId:
                                type: string
                                example: a1350b49-eb8e-3500-9e43-01f5493c91c1
                              startDate:
                                type: integer
                                example: 1709337600
                                default: 0
                              endDate:
                                type: integer
                                example: 1709510400
                                default: 0
                              earnCount:
                                type: integer
                                example: 0
                                default: 0
                              constraintType:
                                type: string
                                example: BADGE_FIXED_WINDOW
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 0
                              default: 0
                            size:
                              type: integer
                              example: 30
                              default: 0
                            total:
                              type: integer
                              example: 1
                              default: 0
                            totalPages:
                              type: integer
                              example: 1
                              default: 0
                    errors:
                      type: array
                    warnings:
                      type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: shell
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/badgeMeta/getFixedWindowDetails?badgeMetaId=69381220cebb9648d8974518'"
          name: Sample request
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
