openapi: 3.1.0
info:
  title: Get Point Allocation Details by Event ID
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /x/neo/pointsAllocation/event:
    get:
      summary: Get Point Allocation Details by Event ID
      description: ''
      operationId: get-point-allocation-event-id-global
      parameters:
      - name: entity_id
        in: query
        description: "Specifies the identifier used to fetch event-specific details.\
          \ This can be one of the following:  The event ID of the event, such as\
          \ TransactionAdd or a behavioral event  The unique ID of the event  The\
          \ server-generated request ID of a behavioral event"
        required: true
        schema:
          type: string
      - name: customer_id
        in: query
        description: Unique Customer ID
        required: true
        schema:
          type: integer
          format: int64
      - name: event_type_id
        in: query
        description: Unique identifier for the type of event.
        required: true
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        description: "Retrieve details of a specific page. Page count starts from\
          \ 1.  Example: page=2 retrieves data on page 2."
        schema:
          type: integer
          format: int32
      - name: count
        in: query
        description: Number of results to display per page. The default value is 10.
          The maximum supported value is 100.
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample Response:
                  value: "[\n    {\n        \"till_id\": 50140377,\n        \"point_category_id\"\
                    : 17383,\n        \"program_id\": 2282,\n        \"event_log_id\"\
                    : 10072893,\n        \"event_type_id\": 15,\n        \"points_source_type_id\"\
                    : 1,\n        \"original_points\": 0,\n        \"awarded_date\"\
                    : 1648489472000,\n        \"returned_exclusive_value\": 0,\n \
                    \       \"points_source_id\": 2148434124,\n        \"id\": 31787856,\n\
                    \        \"cps_id\": 51368957,\n        \"original_customer_id\"\
                    : 374819205,\n        \"expiry_strategy_id\": 105602,\n      \
                    \  \"returned_value\": 0,\n        \"redeemed_exclusive_value\"\
                    : 0,\n        \"expiry_date\": 1648578599000,\n        \"auto_update_time\"\
                    : 1648596913000,\n        \"redeemed_value\": 0,\n        \"expired_exclusive_value\"\
                    : 50,\n        \"allocation_strategy_id\": 105773,\n        \"\
                    points_value\": 0,\n        \"org_id\": 50914,\n        \"expired_value\"\
                    : 0,\n        \"customer_id\": 374819205,\n        \"points_exclusive\"\
                    : 50,\n        \"status\": \"EXPIRED\"\n    }\n]"
              schema:
                type: array
                items:
                  type: object
                  properties:
                    till_id:
                      type: integer
                      example: 50140377
                      default: 0
                    point_category_id:
                      type: integer
                      example: 17383
                      default: 0
                    program_id:
                      type: integer
                      example: 2282
                      default: 0
                    event_log_id:
                      type: integer
                      example: 10072893
                      default: 0
                    event_type_id:
                      type: integer
                      example: 15
                      default: 0
                    points_source_type_id:
                      type: integer
                      example: 1
                      default: 0
                    original_points:
                      type: integer
                      example: 0
                      default: 0
                    awarded_date:
                      type: integer
                      example: 1648489472000
                      default: 0
                    returned_exclusive_value:
                      type: integer
                      example: 0
                      default: 0
                    points_source_id:
                      type: integer
                      example: 2148434124
                      default: 0
                    id:
                      type: integer
                      example: 31787856
                      default: 0
                    cps_id:
                      type: integer
                      example: 51368957
                      default: 0
                    original_customer_id:
                      type: integer
                      example: 374819205
                      default: 0
                    expiry_strategy_id:
                      type: integer
                      example: 105602
                      default: 0
                    returned_value:
                      type: integer
                      example: 0
                      default: 0
                    redeemed_exclusive_value:
                      type: integer
                      example: 0
                      default: 0
                    expiry_date:
                      type: integer
                      example: 1648578599000
                      default: 0
                    auto_update_time:
                      type: integer
                      example: 1648596913000
                      default: 0
                    redeemed_value:
                      type: integer
                      example: 0
                      default: 0
                    expired_exclusive_value:
                      type: integer
                      example: 50
                      default: 0
                    allocation_strategy_id:
                      type: integer
                      example: 105773
                      default: 0
                    points_value:
                      type: integer
                      example: 0
                      default: 0
                    org_id:
                      type: integer
                      example: 50914
                      default: 0
                    expired_value:
                      type: integer
                      example: 0
                      default: 0
                    customer_id:
                      type: integer
                      example: 374819205
                      default: 0
                    points_exclusive:
                      type: integer
                      example: 50
                      default: 0
                    status:
                      type: string
                      example: EXPIRED
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://nightly.api.capillarytech.com/x/neo/pointsAllocation/event?entity_id=hfjWDK0dek&customer_id=374819205&event_type_id=15'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'x-cap-neo-dag-scope:\
            \ global' \\\n--header 'Authorization: Basic RiMDcJkMjM0Yjcw' \\\n--header\
            \ 'Cookie: _cfuvid=aipDF8qJJabNkC6ofNg0_4.3nMtpbVSQI9mVehJNjMw-1749448275226-0.0.1.1-604800000;\
            \ _cfuvid=v57gtlQUtWUPppXkFQEmDIwmVy3hK1VROA7UHTl9fS0-1750313687627-0.0.1.1-604800000'"
          name: Sample Request
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
