openapi: 3.1.0
info:
  title: Get User Recommendations
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/recommendations/user:
    get:
      summary: Get User Recommendations
      description: Retrieves the list of recommended products of a user based on past
        activities such as orders, frequent orders, search items, and trending items.
      operationId: get-user-recommendations
      parameters:
      - name: model
        in: path
        description: Recommendation type to fetch results. <br>you-may-also-like to
          retrieve product recommendations on the user’s currently viewing products
          (during online shopping). trending to retrieve recommended products based
          on previous orders, searches, items viewed, and other user activities. buy-it-again
          to retrieve products that were bought by the user earlier (for reordering).
        schema:
          type: string
          enum:
          - you-may-also-like
          - trending
          - buy-it-again
        required: true
      - name: utype
        in: query
        description: Identifier type to identify customer.
        required: true
        schema:
          type: string
          enum:
          - user_id
          - mobile
          - email
      - name: uvalue
        in: query
        description: The unique identifier value of the utype. For example, if utype=mobile,
          uvalue=9988221100 (mobile number).
        required: true
        schema:
          type: string
      - name: limit
        in: query
        description: Limit the number of results to retrieve. You can retrieve a maximum
          of 25 results.
        required: true
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: Number of results to ignore from top (where the recommendations
          array to start fetching). Set 0 to ignore the first result, 1 to ignore
          the first two results and so on.
        required: true
        schema:
          type: integer
          format: int32
      - name: categories
        in: query
        description: "Filter recommended products by one or more categories. Pass\
          \ comma separated category codes. Maximum of 10 categories are supported.\
          \ Example: categories=Shirts,Bottomwear"
        schema:
          type: array
          items:
            type: string
      - name: stores
        in: query
        description: "Filter products by stores. Pass comma separated store codes.\
          \ Max limit is 10. Example: stores=store.1,store.2"
        schema:
          type: array
          items:
            type: string
      - name: deviceLocation
        in: query
        description: NA
        schema:
          type: array
          items:
            type: string
      - name: deviceType
        in: query
        description: NA
        schema:
          type: string
      - name: X-CAP-API-AUTH-ENTITY-ID
        in: header
        description: Unique Till ID used for authentication.
        required: true
        schema:
          type: string
      - name: X-CAP-API-AUTH-ORG-ID
        in: header
        description: Unique Org ID used for authentication.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample Response:
                  value: "{\n   \"status\":{\n      \"success\":true,\n      \"code\"\
                    :200\n   },\n   \"group\":\"TEST\",\n   \"boxType\":\"you-may-also-like\"\
                    ,\n   \"totalResults\":2,\n   \"recommendedItems\":{\n      \"\
                    items\":[\n         {\n            \"sku\":\"564714\",\n     \
                    \       \"score\":10,\n            \"rank\":1,\n            \"\
                    values\":{\n               \"name\":\"T-Shirts\",\n          \
                    \     \"description\":\"Reebok T-Shirts\",\n               \"\
                    categories\":[\n                  \"Shirts\"\n               ],\n\
                    \               \"image\":{\n                  \"label\":\"\"\
                    ,\n                  \"url\":\"\"\n               },\n       \
                    \        \"smallImage\":{\n                  \"label\":\"\",\n\
                    \                  \"url\":\"\"\n               },\n         \
                    \      \"productUrl\":\"\"\n            }\n         },\n     \
                    \    {\n            \"sku\":\"564716\",\n            \"score\"\
                    :9,\n            \"rank\":2,\n            \"values\":{\n     \
                    \          \"name\":\"Trackpants\",\n               \"description\"\
                    :\"Puma Trackpants\",\n               \"categories\":[\n     \
                    \             \"Bottomwear\"\n               ],\n            \
                    \   \"image\":{\n                  \"label\":\"\",\n         \
                    \         \"url\":\"\"\n               },\n               \"smallImage\"\
                    :{\n                  \"label\":\"\",\n                  \"url\"\
                    :\"\"\n               },\n               \"productUrl\":\"\"\n\
                    \            }\n         }\n      ]\n   }\n}\n"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                  group:
                    type: string
                    example: TEST
                  boxType:
                    type: string
                    example: you-may-also-like
                  totalResults:
                    type: integer
                    example: 2
                    default: 0
                  recommendedItems:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            sku:
                              type: string
                              example: '564714'
                            score:
                              type: integer
                              example: 10
                              default: 0
                            rank:
                              type: integer
                              example: 1
                              default: 0
                            values:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: T-Shirts
                                description:
                                  type: string
                                  example: Reebok T-Shirts
                                categories:
                                  type: array
                                  items:
                                    type: string
                                    example: Shirts
                                image:
                                  type: object
                                  properties:
                                    label:
                                      type: string
                                      example: ''
                                    url:
                                      type: string
                                      example: ''
                                smallImage:
                                  type: object
                                  properties:
                                    label:
                                      type: string
                                      example: ''
                                    url:
                                      type: string
                                      example: ''
                                productUrl:
                                  type: string
                                  example: ''
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: html
          code: "https://incrm.cc.capillarytech.com/api_gateway/v1/recommendations/user/you-may-also-like?utype=user_id&uvalue=123456&limit=5&offset=0&categories"
          name: Sample Request URL
        samples-languages:
        - html
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
