openapi: 3.1.0
info:
  title: Add Promotion Redemption
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/promotions/redemptions:
    post:
      summary: Add Promotion Redemption
      description: ''
      operationId: add-promotion-redemption
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Promotion ID not found for the org:
                  value: "{\n    \"timestamp\": 1737615222993,\n    \"errorCode\"\
                    : 400,\n    \"message\": \"Validation Failed\",\n    \"errorDetails\"\
                    : [\n        \"Promotion with ids : [674fbb982335bd1d58a8c2a4,\
                    \ 674fbb982335bd1d58a8c2a4] not found for org : 4000004 .\"\n\
                    \    ]\n}"
              schema:
                type: object
                properties:
                  timestamp:
                    type: integer
                    example: 1737615222993
                    default: 0
                  errorCode:
                    type: integer
                    example: 400
                    default: 0
                  message:
                    type: string
                    example: Validation Failed
                  errorDetails:
                    type: array
                    items:
                      type: string
                      example: "Promotion with ids : [674fbb982335bd1d58a8c2a4, 674fbb982335bd1d58a8c2a4]\
                        \ not found for org : 4000004 ."
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/promotions/redemptions'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'X-CAP-API-AUTH-ORG-ID:\
            \ 4000004' \\\n--header 'Authorization: Basic YXV0b3NblahblahjIwMmNiOTYyYWM1OTA3NWI5NjRiMDcxNTJkMjM0Yjcw'\
            \ \\\n--header 'Cookie: _cfuvid=wyOhPjyopEethoQrBBNm9fzccPfMP6H1FD60qRHEwJU-1737534439107-0.0.1.1-604800000'\
            \ \\\n--data '{\n  \"customerIdentifierValue\" : \"917214306639\",  \n\
            \  \"customerIdentifierType\" : \"mobile\",\n  \"customerId\" : \"-1\"\
            ,\n  \"transactionIdentifier\" : \"2151411843\",\n  \"transactionNumber\"\
            \ : \"215141171123\",\n   \"transactionDate\":1733307699000,  \n   \"\
            amount\":200,\n   \"lineItems\" : [\n    {\n        \"sku\":\"Sku#Fuel\"\
            ,  \n        \"promotionId\":\"674fbb982335bd1d58a8c2a4\",   \n      \
            \  \"earnedPromotionId\":\"674d9b222335bd1d58a8c09c\",  \n        \"redemptionCount\"\
            :1,\n        \"discount\":100,\n        \"discountAppliedOnQuantity\"\
            :1,\n        \"promotionAppliedOnQuantity\":1\n     }\n   ],\n   \"redemptions\"\
            \ : [\n      {\n        \"sku\":\"Sku#Fuel\",  \n        \"promotionId\"\
            :\"674fbb982335bd1d58a8c2a4\",   \n        \"redemptionCount\":1,\n  \
            \      \"discount\":100,\n        \"discountAppliedOnQuantity\":1,\n \
            \       \"promotionAppliedOnQuantity\":1\n     }\n   ]\n}'"
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
