openapi: 3.1.0
info:
  title: Create Reward Category
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/metadata/category/create:
    post:
      summary: Create Reward Category
      description: Create a new reward category.
      operationId: create-reward-category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - brandId
              - name
              properties:
                brandId:
                  type: integer
                  description: Unique identifier for the brand.
                  format: int64
                name:
                  type: string
                  description: Name of the reward category to be created.
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample Response:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 2002,\n        \"message\": \"Category save successfully\"\
                    \n    },\n    \"category\": {\n        \"id\": 129,\n        \"\
                    name\": \"general\",\n        \"enabled\": true\n    }\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 2002
                        default: 0
                      message:
                        type: string
                        example: Category save successfully
                  category:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 129
                        default: 0
                      name:
                        type: string
                        example: general
                      enabled:
                        type: boolean
                        example: true
                        default: true
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/metadata/category/create'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Accept:\
            \ */*' \\\n--header 'Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg='\
            \ \\\n--header 'Cookie: _cfuvid=3BPRCKcXmguhyneZhg0pLHUUOWEZslsUp2nfMzbbgvA-1750919264238-0.0.1.1-604800000'\
            \ \\\n--data '{\n  \"brandId\": 61,\n  \"name\": \"General\"\n}'"
          name: Sample Request
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
