openapi: 3.1.0
info:
  title: Create badges group
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/group:
    post:
      summary: Create badges group
      description: ''
      operationId: create-badges-group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              - rank
              properties:
                name:
                  type: string
                  description: Name of the group
                rank:
                  type: string
                  description: Rank of the group
            examples:
              Request Example:
                value:
                  name: skjhfdjfhgiok
                  rank: 214748364
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response:
                  value:
                    data:
                      id: 69708faa0772ad476ecf8511
                      orgId: 100737
                      name: skjhfdjfhgiok
                      rank: 214748364
                      createdBy: 75197372
                      createdOn: 1768984490.85601
                      createdOnISO: '2026-01-21T08:34:50Z'
                      lastUpdatedBy: 75197372
                      lastUpdatedOn: 1768984490.85601
                      lastUpdatedOnISO: '2026-01-21T08:34:50Z'
                      isActive: true
                    errors: []
                    warnings: []
                  summary: Sample response
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 6581281e8f68666070de15c5
                      orgId:
                        type: integer
                        example: 50156
                        default: 0
                      name:
                        type: string
                        example: GROUP_RANK_4
                      rank:
                        type: integer
                        example: 2
                        default: 0
                      createdBy:
                        type: integer
                        example: 123
                        default: 0
                      createdOn:
                        type: number
                        example: 1702963230.96642
                        default: 0
                      lastUpdatedBy:
                        type: integer
                        example: 123
                        default: 0
                      lastUpdatedOn:
                        type: number
                        example: 1702963230.96642
                        default: 0
                      isActive:
                        type: boolean
                        example: true
                        default: true
                  errors:
                    type: array
                  warnings:
                    type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
