openapi: 3.1.0
info:
  title: Create Rich Text Content Metadata for Rewards
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/brand/richContentMeta:
    post:
      summary: Create Rich Text Content Metadata for Rewards
      description: ''
      operationId: create-rich-content-meta
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"id\": 6,\n    \"name\": \"RCtest\",\n    \"description\"\
                    : \"RC2_desc\",\n    \"isMandatory\": true,\n    \"isActive\"\
                    : false,\n    \"scope\": \"REWARD\",\n    \"defaultValue\": \"\
                    en\",\n    \"createdBy\": 75161973,\n    \"createdOn\": 1743258861441,\n\
                    \    \"lastUpdatedBy\": 75161973,\n    \"lastUpdatedOn\": 1743258861441\n\
                    }"
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 6
                    default: 0
                  name:
                    type: string
                    example: RCtest
                  description:
                    type: string
                    example: RC2_desc
                  isMandatory:
                    type: boolean
                    example: true
                    default: true
                  isActive:
                    type: boolean
                    example: false
                    default: true
                  scope:
                    type: string
                    example: REWARD
                  defaultValue:
                    type: string
                    example: en
                  createdBy:
                    type: integer
                    example: 75161973
                    default: 0
                  createdOn:
                    type: integer
                    example: 1743258861441
                    default: 0
                  lastUpdatedBy:
                    type: integer
                    example: 75161973
                    default: 0
                  lastUpdatedOn:
                    type: integer
                    example: 1743258861441
                    default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/brand/richContentMeta'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Accept:\
            \ */*' \\\n--header 'Authorization: Basic YXV0b3N0b3JlMS50aWxsMS0xNjgwMTY5MjIxOjIwMmNiOTYyYWM1OTA3NWI5NjRiMDcxNTJkMjM0Yjcw'\
            \ \\\n--header 'X-CAP-API-AUTH-ORG-ID: 50339' \\\n--data '{\n    \"name\"\
            : \"RCtest\",\n    \"description\": \"RC2_desc\",\n    \"isMandatory\"\
            : true,\n    \"isActive\": true,\n    \"scope\": \"REWARD\",\n    \"defaultValue\"\
            : \"en\"\n}'"
          name: create rich content
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
