openapi: 3.1.0
info:
  title: Claim badge
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/badgeMeta/{badgeId}/claim:
    post:
      summary: Claim badge
      description: ''
      operationId: claim-badge
      parameters:
      - name: badgeId
        in: path
        description: Unique Identifier for the badge.Unique Identifier for the badge.
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - ownerType
              - referenceId
              properties:
                ownerType:
                  type: string
                  description: The module for which the badge is being claimed.
                  enum:
                  - LOYALTY/REFERRAL_CAMPAIGNS/JOURNEYS/AUDIENCE_CAMPAIGNS/   REWARDS_CATALOG/
                    GOODWILL_MODULE/ MILESTONES
                referenceId:
                  type: string
                  description: A unique identifier associated with the owner.
            examples:
              Request body:
                value:
                  ownerType: Loyalty
                  referenceId: '123'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data:
                      ownerType: Loyalty
                      referenceId: '123'
                      isActive: true
                    errors: null
                    warnings: []
              schema:
                oneOf:
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId: {}
                        ownerType:
                          type: string
                          example: Loyalty
                        referenceId:
                          type: string
                          example: '626'
                    errors: {}
                    warnings:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 900
                            default: 0
                          message:
                            type: string
                            example: Badge is already claimed by this owner
                - type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 653df084b3cda7078c7c68f1
                        ownerType:
                          type: string
                          example: Loyalty
                        referenceId:
                          type: string
                          example: '123'
                    errors: {}
                    warnings:
                      type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"data\": null,\n    \"errors\": [\n        {\n \
                    \           \"code\": 400,\n            \"message\": \"Invalid\
                    \ enum value: 'LOYALTY' for the field: 'ownerType'. The value\
                    \ must be one of: [Loyalty, Referral_Campaigns, Journeys, Audience_Campaigns,\
                    \ Rewards_Catalog, Goodwill_Module, Milestones].\",\n        \
                    \    \"reference\": null\n        }\n    ],\n    \"warnings\"\
                    : null\n}"
              schema:
                oneOf:
                - type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 717
                            default: 0
                          message:
                            type: string
                            example: Owner id is mandatory
                          reference:
                            type: string
                            example: referenceId
                    warnings: {}
                - type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 400
                            default: 0
                          message:
                            type: string
                            example: 'Invalid enum value: ''LOYALTY'' for the field:
                              ''ownerType''. The value must be one of: [Loyalty, Referral_Campaigns,
                              Journeys, Audience_Campaigns, Rewards_Catalog, Goodwill_Module,
                              Milestones].'
                          reference: {}
                    warnings: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/badgeMeta/69381220cebb9648d8974518/claim'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Authorization: Basic bWFkaHVfcjMjU2YQ==' \\\n--header 'Cookie: _cfuvid=h41NNNJlaGGCp71UuFTcMjP3q.OYkoR9IigSN5f_pGY-1768819014360-0.0.1.1-604800000'\
            \ \\\n--data '{\n    \"ownerType\": \"Loyalty\",\n    \"referenceId\"\
            : \"123\"\n}'"
          language: shell
          name: Sample request
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
