openapi: 3.1.0
info:
  title: Deactivate search criteria
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/cortex/v1/criteria/{id}:
    delete:
      summary: Deactivate search criteria
      description: This API enables you to deactivate a search criteria.
      operationId: deactivate-search-criteria
      parameters:
      - name: id
        in: path
        description: The unique identifier of the search criteria
        schema:
          type: string
        required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"data\": {\n        \"id\": \"64b117d756bb3f20312aae7f\"\
                    ,\n        \"orgId\": 2064,\n        \"name\": \"criteria_1231_1\"\
                    ,\n        \"entityType\": \"TRANSACTION\",\n        \"fieldDefinitions\"\
                    : [\n            {\n                \"fieldId\": \"destination\"\
                    ,\n                \"fieldAlias\": \"destination\",\n        \
                    \        \"dataSourceDetails\": {\n                    \"fieldReference\"\
                    : \"extendedFields.destination\"\n                },\n       \
                    \         \"dataType\": \"STRING\"\n            },\n         \
                    \   {\n                \"fieldId\": \"origin\",\n            \
                    \    \"fieldAlias\": \"origin\",\n                \"dataSourceDetails\"\
                    : {\n                    \"fieldReference\": \"extendedFields.origin\"\
                    \n                },\n                \"dataType\": \"STRING\"\
                    \n            }\n        ],\n        \"searchDataPolicy\": {\n\
                    \            \"dataRetentionPolicy\": {\n                \"unit\"\
                    : \"DAYS\",\n                \"value\": 30\n            },\n \
                    \           \"expireDataFrom\": \"CREATE\"\n        },\n     \
                    \   \"active\": false,\n        \"bulkJobStatus\": \"IN_PROGRESS\"\
                    ,\n        \"auditInfo\": {\n            \"createdOn\": \"2023-07-14T09:39:35.353+00:00\"\
                    ,\n            \"createdBy\": 13425520,\n            \"lastUpdatedOn\"\
                    : \"2023-07-14T12:20:35.994+00:00\",\n            \"lastUpdatedBy\"\
                    : -1\n        }\n    },\n    \"errors\": []\n}"
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 64b117d756bb3f20312aae7f
                      orgId:
                        type: integer
                        example: 2064
                        default: 0
                      name:
                        type: string
                        example: criteria_1231_1
                      entityType:
                        type: string
                        example: TRANSACTION
                      fieldDefinitions:
                        type: array
                        items:
                          type: object
                          properties:
                            fieldId:
                              type: string
                              example: destination
                            fieldAlias:
                              type: string
                              example: destination
                            dataSourceDetails:
                              type: object
                              properties:
                                fieldReference:
                                  type: string
                                  example: extendedFields.destination
                            dataType:
                              type: string
                              example: STRING
                      searchDataPolicy:
                        type: object
                        properties:
                          dataRetentionPolicy:
                            type: object
                            properties:
                              unit:
                                type: string
                                example: DAYS
                              value:
                                type: integer
                                example: 30
                                default: 0
                          expireDataFrom:
                            type: string
                            example: CREATE
                      active:
                        type: boolean
                        example: false
                        default: true
                      bulkJobStatus:
                        type: string
                        example: IN_PROGRESS
                      auditInfo:
                        type: object
                        properties:
                          createdOn:
                            type: string
                            example: '2023-07-14T09:39:35.353+00:00'
                          createdBy:
                            type: integer
                            example: 13425520
                            default: 0
                          lastUpdatedOn:
                            type: string
                            example: '2023-07-14T12:20:35.994+00:00'
                          lastUpdatedBy:
                            type: integer
                            example: -1
                            default: 0
                  errors:
                    type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: 'https://apac.api.capillarytech.com/api_gateway/cortex/v1/criteria/64b117d756bb3f20312aae7f'' '
          name: Delete a search criteria sample CURL
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
