openapi: 3.1.0
info:
  title: Get available brand rewards
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  "/api_gateway/rewards/core/v1/reward/brand/{brandId}/available":
    get:
      summary: Get available brand rewards
      description: ''
      operationId: get-available-brand-rewards
      parameters:
      - name: brandId
        in: path
        description: Unique identifier of the brand.
        schema:
          type: integer
          format: int64
        required: true
      - name: startDate
        in: query
        required: true
        schema:
          type: string
      - name: endDate
        in: query
        required: true
        schema:
          type: string
      - name: language
        in: query
        description: Filters the response based on the reward language. Use this parameter
          to retrieve rewards in a specific language. For example, to display rewards
          in English, set the parameter to en
        schema:
          type: string
          enum:
          - ''
          default: en
      - name: "yYYY-MM-DDTHH:MMZ"
        in: query
        schema:
          type: string
        required: false
      - name: "yYYY-MM-DDTHH:MMZ"
        in: query
        schema:
          type: string
        required: false
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 6101,\n        \"message\": \"Reward details fetched\
                    \ successfully\"\n    },\n    \"rewardList\": [\n        {\n \
                    \           \"id\": 4,\n            \"name\": \"10% off on clothing\"\
                    ,\n            \"status\": \"ENDED\",\n            \"startTime\"\
                    : \"2021-05-10 18:45:14\",\n            \"endTime\": \"2021-05-10\
                    \ 18:45:14\",\n            \"type\": \"VOUCHER\",\n          \
                    \  \"priority\": 1,\n            \"enabled\": false,\n       \
                    \     \"intouchPoints\": 100,\n            \"redemptionType\"\
                    : \"INTOUCH_REWARD\",\n            \"groups\": [],\n         \
                    \   \"rewardRank\": null,\n            \"customFields\": {},\n\
                    \            \"paymentConfigs\": null\n        },\n        {\n\
                    \            \"id\": 7,\n            \"name\": \"15% off on Skinny\
                    \ Jeans\",\n            \"status\": \"ENDED\",\n            \"\
                    startTime\": \"2021-05-10 18:50:08\",\n            \"endTime\"\
                    : \"2021-05-10 18:50:08\",\n            \"type\": \"VOUCHER\"\
                    ,\n            \"priority\": 2,\n            \"enabled\": false,\n\
                    \            \"intouchPoints\": 200,\n            \"redemptionType\"\
                    : \"INTOUCH_REWARD\",\n            \"groups\": [],\n         \
                    \   \"rewardRank\": null,\n            \"customFields\": {},\n\
                    \            \"paymentConfigs\": null\n        },\n        {\n\
                    \            \"id\": 8,\n            \"name\": \"200 off on shirts\"\
                    ,\n            \"status\": \"ENDED\",\n            \"startTime\"\
                    : \"2021-05-10 18:54:18\",\n            \"endTime\": \"2021-05-10\
                    \ 18:54:18\",\n            \"type\": \"VOUCHER\",\n          \
                    \  \"priority\": 3,\n            \"enabled\": false,\n       \
                    \     \"intouchPoints\": 500,\n            \"redemptionType\"\
                    : \"INTOUCH_REWARD\",\n            \"groups\": [],\n         \
                    \   \"rewardRank\": null,\n            \"customFields\": {},\n\
                    \            \"paymentConfigs\": null\n        },\n        {\n\
                    \            \"id\": 9,\n            \"name\": \"Flat 50% off\
                    \ on shoes\",\n            \"status\": \"ENDED\",\n          \
                    \  \"startTime\": \"2021-05-10 19:13:16\",\n            \"endTime\"\
                    : \"2021-05-10 19:13:16\",\n            \"type\": \"VOUCHER\"\
                    ,\n            \"priority\": 4,\n            \"enabled\": false,\n\
                    \            \"intouchPoints\": 300,\n            \"redemptionType\"\
                    : \"INTOUCH_REWARD\",\n            \"groups\": [],\n         \
                    \   \"rewardRank\": null,\n            \"customFields\": {},\n\
                    \            \"paymentConfigs\": null\n        },\n        {\n\
                    \            \"id\": 206280,\n            \"name\": \"Eggo\",\n\
                    \            \"status\": \"ENDED\",\n            \"startTime\"\
                    : \"2024-07-26 16:15:00\",\n            \"endTime\": \"2024-07-26\
                    \ 16:15:00\",\n            \"type\": \"VOUCHER\",\n          \
                    \  \"priority\": 1,\n            \"enabled\": true,\n        \
                    \    \"intouchPoints\": 0,\n            \"redemptionType\": \"\
                    INTOUCH_REWARD\",\n            \"groups\": [\n               \
                    \ {\n                    \"groupName\": \"Kellanova Rewards\"\
                    ,\n                    \"groupRank\": null\n                }\n\
                    \            ],\n            \"rewardRank\": 5,\n            \"\
                    customFields\": {},\n            \"paymentConfigs\": [\n     \
                    \           {\n                    \"paymentMode\": \"FREE\",\n\
                    \                    \"id\": 336\n                }\n        \
                    \    ]\n        },\n        {\n            \"id\": 206281,\n \
                    \           \"name\": \"Poptarts\",\n            \"status\": \"\
                    ENDED\",\n            \"startTime\": \"2024-07-26 16:15:00\",\n\
                    \            \"endTime\": \"2024-07-26 16:15:00\",\n         \
                    \   \"type\": \"VOUCHER\",\n            \"priority\": 1,\n   \
                    \         \"enabled\": true,\n            \"intouchPoints\": 0,\n\
                    \            \"redemptionType\": \"INTOUCH_REWARD\",\n       \
                    \     \"groups\": [\n                {\n                    \"\
                    groupName\": \"Kellanova Rewards\",\n                    \"groupRank\"\
                    : null\n                }\n            ],\n            \"rewardRank\"\
                    : 1,\n            \"customFields\": {},\n            \"paymentConfigs\"\
                    : [\n                {\n                    \"paymentMode\": \"\
                    FREE\",\n                    \"id\": 337\n                }\n\
                    \            ]\n        },\n        {\n            \"id\": 206609,\n\
                    \            \"name\": \"testreward1\",\n            \"status\"\
                    : \"LIVE\",\n            \"startTime\": \"2024-07-26 07:38:00\"\
                    ,\n            \"endTime\": \"2024-07-26 07:38:00\",\n       \
                    \     \"type\": \"VOUCHER\",\n            \"priority\": 1,\n \
                    \           \"enabled\": true,\n            \"intouchPoints\"\
                    : 500,\n            \"redemptionType\": \"INTOUCH_REWARD\",\n\
                    \            \"groups\": [],\n            \"rewardRank\": 1,\n\
                    \            \"customFields\": {},\n            \"paymentConfigs\"\
                    : [\n                {\n                    \"paymentMode\": \"\
                    POINTS\",\n                    \"id\": 344,\n                \
                    \    \"points\": 100.0000\n                }\n            ]\n\
                    \        },\n        {\n            \"id\": 206610,\n        \
                    \    \"name\": \"$10 cash back reward\",\n            \"status\"\
                    : \"LIVE\",\n            \"startTime\": \"2024-07-26 07:38:00\"\
                    ,\n            \"endTime\": \"2024-07-26 07:38:00\",\n       \
                    \     \"type\": \"VOUCHER\",\n            \"priority\": 1,\n \
                    \           \"enabled\": true,\n            \"intouchPoints\"\
                    : 1000,\n            \"redemptionType\": \"INTOUCH_REWARD\",\n\
                    \            \"groups\": [],\n            \"rewardRank\": null,\n\
                    \            \"customFields\": {},\n            \"paymentConfigs\"\
                    : [\n                {\n                    \"paymentMode\": \"\
                    POINTS\",\n                    \"id\": 345,\n                \
                    \    \"points\": 100.0000\n                }\n            ]\n\
                    \        },\n        {\n            \"id\": 206610,\n        \
                    \    \"name\": \"$10 Nordstrom Notes\",\n            \"status\"\
                    : \"LIVE\",\n            \"startTime\": \"2024-07-26 07:38:00\"\
                    ,\n            \"endTime\": \"2024-07-26 07:38:00\",\n       \
                    \     \"type\": \"VOUCHER\",\n            \"priority\": 1,\n \
                    \           \"enabled\": true,\n            \"intouchPoints\"\
                    : 1000,\n            \"redemptionType\": \"INTOUCH_REWARD\",\n\
                    \            \"groups\": [],\n            \"rewardRank\": null,\n\
                    \            \"customFields\": {},\n            \"paymentConfigs\"\
                    : [\n                {\n                    \"paymentMode\": \"\
                    POINTS\",\n                    \"id\": 345,\n                \
                    \    \"points\": 100.0000\n                }\n            ]\n\
                    \        }\n    ]\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 6101
                        default: 0
                      message:
                        type: string
                        example: Reward details fetched successfully
                  rewardList:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                          default: 0
                        name:
                          type: string
                          example: 10% off on clothing
                        status:
                          type: string
                          example: ENDED
                        startTime:
                          type: string
                          example: "2021-05-10 18:45:14"
                        endTime:
                          type: string
                          example: "2021-05-10 18:45:14"
                        type:
                          type: string
                          example: VOUCHER
                        priority:
                          type: integer
                          example: 1
                          default: 0
                        enabled:
                          type: boolean
                          example: false
                          default: true
                        intouchPoints:
                          type: integer
                          example: 100
                          default: 0
                        redemptionType:
                          type: string
                          example: INTOUCH_REWARD
                        groups:
                          type: array
                        rewardRank: {}
                        customFields:
                          type: object
                          properties: {}
                        paymentConfigs: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": false,\n    \
                    \    \"code\": 400,\n        \"message\": \"start or end date\
                    \ should be passed in proper format yyyy-MM-dd'T'HH:mm'Z'\"\n\
                    \    }\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                        default: true
                      code:
                        type: integer
                        example: 400
                        default: 0
                      message:
                        type: string
                        example: "start or end date should be passed in proper format\
                          \ yyyy-MM-dd'T'HH:mm'Z'"
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/brand/1/available?startDate=2023-04-20T08:55Z&endDate=2024-07-30T08:55Z'\
            \ \\\n--header 'Accept: */*' \\\n--header 'Authorization: Basic aWFtc2hpdmFhbms6NblahblahDM4ZjhlMzRkNWI1YTI5MWY='\
            \ \\\n--header 'Cookie: _cfuvid=NJfT4sKrp52F91VHc.jjVnfGMHiYjCsRisiSMqu5.eg-1734413549869-0.0.1.1-604800000'\
            \ \\\n--data ''"
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
