openapi: 3.1.0
info:
  title: Get Reward Category
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  "/api_gateway/rewards/core/v1/metadata/categories/brand/{brandId}":
    get:
      summary: Get Reward Category
      description: Get reward categories for a particluar brand.
      operationId: get-reward-category
      parameters:
      - name: brandId
        in: path
        description: Unique identifier for the brand.
        schema:
          type: integer
          format: int64
        required: true
      - name: brandName
        in: path
        description: Name of the brand for which you want to retrieve the reward categories.
        schema:
          type: string
        required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 200,\n        \"message\": \"Category fetched successfully\"\
                    \n    },\n    \"categoryList\": [\n        {\n            \"id\"\
                    : 128,\n            \"name\": \"tickets\",\n            \"enabled\"\
                    : false\n        },\n        {\n            \"id\": 111,\n   \
                    \         \"name\": \"training\",\n            \"enabled\": true\n\
                    \        }\n    ]\n}"
                Invalid brandId:
                  value: "{\n    \"status\": {\n        \"success\": false,\n    \
                    \    \"code\": 3004,\n        \"message\": \"Brand not found\"\
                    \n    },\n    \"categoryList\": null\n}"
                With sortBy=lastUpdatedOn:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 200,\n        \"message\": \"Category fetched successfully\"\
                    \n    },\n    \"categoryList\": [\n        {\n            \"id\"\
                    : 170,\n            \"name\": \"toys\",\n            \"enabled\"\
                    : true,\n            \"createdOn\": 1735816377000,\n         \
                    \   \"lastUpdatedOn\": 1735816377000,\n            \"createdBy\"\
                    : null,\n            \"lastUpdatedBy\": null,\n            \"\
                    createdOnDateTime\": \"2025-01-02T11:12:57Z\",\n            \"\
                    lastUpdatedOnDateTime\": \"2025-01-02T11:12:57Z\"\n        },\n\
                    \        {\n            \"id\": 229,\n            \"name\": \"\
                    joreward\",\n            \"enabled\": true,\n            \"createdOn\"\
                    : 1741059743000,\n            \"lastUpdatedOn\": 1741059743000,\n\
                    \            \"createdBy\": null,\n            \"lastUpdatedBy\"\
                    : null,\n            \"createdOnDateTime\": \"2025-03-04T03:42:23Z\"\
                    ,\n            \"lastUpdatedOnDateTime\": \"2025-03-04T03:42:23Z\"\
                    \n        },\n        {\n            \"id\": 251,\n          \
                    \  \"name\": \"docdemo\",\n            \"enabled\": true,\n  \
                    \          \"createdOn\": 1742387687000,\n            \"lastUpdatedOn\"\
                    : 1742387687000,\n            \"createdBy\": null,\n         \
                    \   \"lastUpdatedBy\": null,\n            \"createdOnDateTime\"\
                    : \"2025-03-19T12:34:47Z\",\n            \"lastUpdatedOnDateTime\"\
                    : \"2025-03-19T12:34:47Z\"\n        }\n    ]\n}"
              schema:
                oneOf:
                - type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 200
                          default: 0
                        message:
                          type: string
                          example: Category fetched successfully
                    categoryList:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 128
                            default: 0
                          name:
                            type: string
                            example: tickets
                          enabled:
                            type: boolean
                            example: false
                            default: true
                - title: Invalid brandId
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3004
                          default: 0
                        message:
                          type: string
                          example: Brand not found
                    categoryList: {}
                - title: With sortBy=lastUpdatedOn
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 200
                          default: 0
                        message:
                          type: string
                          example: Category fetched successfully
                    categoryList:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 170
                            default: 0
                          name:
                            type: string
                            example: toys
                          enabled:
                            type: boolean
                            example: true
                            default: true
                          createdOn:
                            type: integer
                            example: 1735816377000
                            default: 0
                          lastUpdatedOn:
                            type: integer
                            example: 1735816377000
                            default: 0
                          createdBy: {}
                          lastUpdatedBy: {}
                          createdOnDateTime:
                            type: string
                            example: "2025-01-02T11:12:57Z"
                          lastUpdatedOnDateTime:
                            type: string
                            example: "2025-01-02T11:12:57Z"
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/metadata/categories/brand/55'\
            \ \\\n--header 'Accept: */*' \\\n--header 'Authorization: Basic Ymxpc3MZTJmNGRjNzU5MWI1NzY='"
          name: Sample Request
        - language: curl
          code: "curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/metadata/categories/brand/55?orderBy=ASC&sortBy=lastUpdatedOn'\
            \ \\\n--header 'Accept: */*' \\\n--header 'Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg='\
            \ \\\n--header 'Cookie: _cfuvid=fUmBd935rmGsApqf1rYLG1M2QWI_fYSTy7P0wHTVZIs-1747377050702-0.0.1.1-604800000'"
          name: With sortBy=lastUpdatedOn
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
