openapi: 3.1.0
info:
  title: Get fulfillment status
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/fulfillmentStatus:
    get:
      summary: Get fulfillment status
      description: ''
      operationId: get-fulfillment-status
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "[\n    {\n        \"id\": 164,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERED\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75154383,\n        \"createdOn\": 1736405355000,\n\
                    \        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\",\n  \
                    \      \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    },\n    {\n        \"id\": 163,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERING SOON\",\n        \"isEnabled\"\
                    : true,\n        \"createdBy\": 75154383,\n        \"createdOn\"\
                    : 1736405355000,\n        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    ,\n        \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    },\n    {\n        \"id\": 252,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"it is here\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75155282,\n        \"createdOn\": 1741934183000,\n\
                    \        \"createdOnDateTime\": \"2025-03-14T06:36:23Z\",\n  \
                    \      \"lastUpdatedBy\": 75155282,\n        \"lastUpdatedOn\"\
                    : 1741934183000,\n        \"lastUpdatedOnDateTime\": \"2025-03-14T06:36:23Z\"\
                    \n    },\n    {\n        \"id\": 253,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"it is here now\",\n        \"isEnabled\"\
                    : true,\n        \"createdBy\": 75155282,\n        \"createdOn\"\
                    : 1741934783000,\n        \"createdOnDateTime\": \"2025-03-14T06:46:23Z\"\
                    ,\n        \"lastUpdatedBy\": 75155282,\n        \"lastUpdatedOn\"\
                    : 1741934783000,\n        \"lastUpdatedOnDateTime\": \"2025-03-14T06:46:23Z\"\
                    \n    },\n    {\n        \"id\": 162,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"ON ITS WAY\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75154383,\n        \"createdOn\": 1736405355000,\n\
                    \        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\",\n  \
                    \      \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    }\n]"
                With sortBy=lastUpdatedOn:
                  value: "[\n    {\n        \"id\": 253,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERED2\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75155282,\n        \"createdOn\": 1741934783000,\n\
                    \        \"createdOnDateTime\": \"2025-03-14T06:46:23Z\",\n  \
                    \      \"lastUpdatedBy\": 75155282,\n        \"lastUpdatedOn\"\
                    : 1741934783000,\n        \"lastUpdatedOnDateTime\": \"2025-03-14T06:46:23Z\"\
                    \n    },\n    {\n        \"id\": 252,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERED1\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75155282,\n        \"createdOn\": 1741934183000,\n\
                    \        \"createdOnDateTime\": \"2025-03-14T06:36:23Z\",\n  \
                    \      \"lastUpdatedBy\": 75155282,\n        \"lastUpdatedOn\"\
                    : 1741934183000,\n        \"lastUpdatedOnDateTime\": \"2025-03-14T06:36:23Z\"\
                    \n    },\n    {\n        \"id\": 164,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERED\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75154383,\n        \"createdOn\": 1736405355000,\n\
                    \        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\",\n  \
                    \      \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    },\n    {\n        \"id\": 163,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"DELIVERING SOON\",\n        \"isEnabled\"\
                    : true,\n        \"createdBy\": 75154383,\n        \"createdOn\"\
                    : 1736405355000,\n        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    ,\n        \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    },\n    {\n        \"id\": 162,\n        \"orgId\": 100737,\n\
                    \        \"name\": \"ON ITS WAY\",\n        \"isEnabled\": true,\n\
                    \        \"createdBy\": 75154383,\n        \"createdOn\": 1736405355000,\n\
                    \        \"createdOnDateTime\": \"2025-01-09T06:49:15Z\",\n  \
                    \      \"lastUpdatedBy\": 75154383,\n        \"lastUpdatedOn\"\
                    : 1736405355000,\n        \"lastUpdatedOnDateTime\": \"2025-01-09T06:49:15Z\"\
                    \n    }\n]"
              schema:
                oneOf:
                - type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 164
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      name:
                        type: string
                        example: DELIVERED
                      isEnabled:
                        type: boolean
                        example: true
                        default: true
                      createdBy:
                        type: integer
                        example: 75154383
                        default: 0
                      createdOn:
                        type: integer
                        example: 1736405355000
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-01-09T06:49:15Z'
                      lastUpdatedBy:
                        type: integer
                        example: 75154383
                        default: 0
                      lastUpdatedOn:
                        type: integer
                        example: 1736405355000
                        default: 0
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-01-09T06:49:15Z'
                - title: With sortBy=lastUpdatedOn
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 253
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      name:
                        type: string
                        example: DELIVERED2
                      isEnabled:
                        type: boolean
                        example: true
                        default: true
                      createdBy:
                        type: integer
                        example: 75155282
                        default: 0
                      createdOn:
                        type: integer
                        example: 1741934783000
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-03-14T06:46:23Z'
                      lastUpdatedBy:
                        type: integer
                        example: 75155282
                        default: 0
                      lastUpdatedOn:
                        type: integer
                        example: 1741934783000
                        default: 0
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-03-14T06:46:23Z'
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: 'curl --location ''https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/fulfillmentStatus''
            \

            --header ''Authorization: Basic aWFtc2hpdmFhbnjknVNKJFVblahDBLAHhlMzRkNWI1YTI5MWY=''
            \

            --header ''Cookie: _cfuvid=YLWKW2g3iSh26hCX0XcFCuh8oQRtUpC5dGAfoYq7hh0-1721653557209-0.0.1.1-604800000'''
        - language: curl
          code: 'curl --location ''https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/fulfillmentStatus?orderBy=DESC&sortBy=lastUpdatedOn''
            \

            --header ''Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg=''
            \

            --header ''Cookie: _cfuvid=YLWKW2g3iSh26hCX0XcFCuh8oQRtUpC5dGAfoYq7hh0-1721653557209-0.0.1.1-604800000;
            _cfuvid=0HswOUeY1hLB1ChixiPHPvEBpkBYBw.OmrLWQyfiBZ0-1747382714367-0.0.1.1-604800000'''
          name: With sortBy=lastUpdatedOn
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
