openapi: 3.1.0
info:
  title: Points - Get points constraints
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/brand/constraints:
    get:
      summary: Points - Get points constraints
      description: ''
      operationId: get-points-constraints
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "[\n    {\n        \"rewardConstraintId\": 10259,\n     \
                    \   \"orgId\": 100458,\n        \"kpi\": \"POINTS\",\n       \
                    \ \"constraintLevel\": \"CUSTOMER_REDEMPTION_TYPE\",\n       \
                    \ \"frequencyType\": \"MONTHLY\",\n        \"constraintLimitValue\"\
                    : 100,\n        \"isActive\": true,\n        \"status\": {\n \
                    \           \"success\": true,\n            \"code\": 0\n    \
                    \    },\n        \"redemptionType\": \"NULL\"\n    },\n    {\n\
                    \        \"rewardConstraintId\": 10857,\n        \"orgId\": 100458,\n\
                    \        \"kpi\": \"POINTS\",\n        \"constraintLevel\": \"\
                    CUSTOMER\",\n        \"frequencyType\": \"DAILY\",\n        \"\
                    constraintLimitValue\": 5,\n        \"isActive\": true,\n    \
                    \    \"intervalValue\": 1,\n        \"status\": {\n          \
                    \  \"success\": true,\n            \"code\": 0\n        }\n  \
                    \  },\n    {\n        \"rewardConstraintId\": 11123,\n       \
                    \ \"orgId\": 100458,\n        \"kpi\": \"POINTS\",\n        \"\
                    constraintLevel\": \"CUSTOMER_REDEMPTION_TYPE\",\n        \"frequencyType\"\
                    : \"DAILY\",\n        \"constraintLimitValue\": 15,\n        \"\
                    isActive\": true,\n        \"intervalValue\": 1,\n        \"status\"\
                    : {\n            \"success\": true,\n            \"code\": 0\n\
                    \        },\n        \"redemptionType\": \"POINTS\"\n    },\n\
                    \    {\n        \"rewardConstraintId\": 11436,\n        \"orgId\"\
                    : 100458,\n        \"kpi\": \"POINTS\",\n        \"constraintLevel\"\
                    : \"CUSTOMER_LOYALTY_PROGRAM\",\n        \"frequencyType\": \"\
                    DAILY\",\n        \"constraintLimitValue\": 15,\n        \"isActive\"\
                    : true,\n        \"intervalValue\": 1,\n        \"status\": {\n\
                    \            \"success\": true,\n            \"code\": 0\n   \
                    \     },\n        \"programId\": \"1680\"\n    },\n    {\n   \
                    \     \"rewardConstraintId\": 11662,\n        \"orgId\": 100458,\n\
                    \        \"kpi\": \"POINTS\",\n        \"constraintLevel\": \"\
                    CUSTOMER_REDEMPTION_TYPE\",\n        \"frequencyType\": \"WEEKLY\"\
                    ,\n        \"constraintLimitValue\": 10,\n        \"isActive\"\
                    : true,\n        \"startDayOfTheWeek\": \"MONDAY\",\n        \"\
                    status\": {\n            \"success\": true,\n            \"code\"\
                    : 0\n        },\n        \"redemptionType\": \"MILES\"\n    },\n\
                    \    {\n        \"rewardConstraintId\": 11664,\n        \"orgId\"\
                    : 100458,\n        \"kpi\": \"POINTS\",\n        \"constraintLevel\"\
                    : \"CUSTOMER_LOYALTY_PROGRAM\",\n        \"frequencyType\": \"\
                    DAILY\",\n        \"constraintLimitValue\": 5,\n        \"isActive\"\
                    : true,\n        \"intervalValue\": 1,\n        \"status\": {\n\
                    \            \"success\": true,\n            \"code\": 0\n   \
                    \     },\n        \"programId\": \"469\"\n    },\n    {\n    \
                    \    \"rewardConstraintId\": 11667,\n        \"orgId\": 100458,\n\
                    \        \"kpi\": \"POINTS\",\n        \"constraintLevel\": \"\
                    CUSTOMER_LABEL\",\n        \"frequencyType\": \"DAILY\",\n   \
                    \     \"constraintLimitValue\": 5,\n        \"isActive\": true,\n\
                    \        \"intervalValue\": 1,\n        \"status\": {\n      \
                    \      \"success\": true,\n            \"code\": 0\n        },\n\
                    \        \"label\": \"Fashion\"\n    },\n    {\n        \"rewardConstraintId\"\
                    : 13059,\n        \"orgId\": 100458,\n        \"kpi\": \"POINTS\"\
                    ,\n        \"constraintLevel\": \"CUSTOMER_TIER\",\n        \"\
                    frequencyType\": \"DAILY\",\n        \"constraintLimitValue\"\
                    : 5,\n        \"isActive\": true,\n        \"intervalValue\":\
                    \ 1,\n        \"status\": {\n            \"success\": true,\n\
                    \            \"code\": 0\n        },\n        \"tierId\": \"1\"\
                    \n    }\n]"
                With sortBy=lastUpdatedOn:
                  value: "[\n    {\n        \"rewardConstraintId\": 34327,\n     \
                    \   \"orgId\": 100737,\n        \"kpi\": \"POINTS\",\n       \
                    \ \"constraintLevel\": \"CUSTOMER_REDEMPTION_TYPE\",\n       \
                    \ \"frequencyType\": \"DAILY\",\n        \"constraintLimitValue\"\
                    : 15,\n        \"isActive\": true,\n        \"intervalValue\"\
                    : 1,\n        \"status\": {\n            \"success\": true,\n\
                    \            \"code\": 0\n        },\n        \"createdOn\": 1747374478000,\n\
                    \        \"lastUpdatedOn\": 1747374478000,\n        \"createdBy\"\
                    : 75161973,\n        \"lastUpdatedBy\": 75161973,\n        \"\
                    createdOnDateTime\": \"2025-05-16T05:47:58Z\",\n        \"lastUpdatedOnDateTime\"\
                    : \"2025-05-16T05:47:58Z\",\n        \"redemptionType\": \"CASH\"\
                    \n    },\n    {\n        \"rewardConstraintId\": 34326,\n    \
                    \    \"orgId\": 100737,\n        \"kpi\": \"POINTS\",\n      \
                    \  \"constraintLevel\": \"CUSTOMER_REDEMPTION_TYPE\",\n      \
                    \  \"frequencyType\": \"DAILY\",\n        \"constraintLimitValue\"\
                    : 15,\n        \"isActive\": true,\n        \"intervalValue\"\
                    : 1,\n        \"status\": {\n            \"success\": true,\n\
                    \            \"code\": 0\n        },\n        \"createdOn\": 1747374467000,\n\
                    \        \"lastUpdatedOn\": 1747374467000,\n        \"createdBy\"\
                    : 75161973,\n        \"lastUpdatedBy\": 75161973,\n        \"\
                    createdOnDateTime\": \"2025-05-16T05:47:47Z\",\n        \"lastUpdatedOnDateTime\"\
                    : \"2025-05-16T05:47:47Z\",\n        \"redemptionType\": \"VOUCHER\"\
                    \n    },\n    {\n        \"rewardConstraintId\": 29700,\n    \
                    \    \"orgId\": 100737,\n        \"kpi\": \"POINTS\",\n      \
                    \  \"constraintLevel\": \"CUSTOMER_REDEMPTION_TYPE\",\n      \
                    \  \"frequencyType\": \"DAILY\",\n        \"constraintLimitValue\"\
                    : 15,\n        \"isActive\": true,\n        \"intervalValue\"\
                    : 1,\n        \"status\": {\n            \"success\": true,\n\
                    \            \"code\": 0\n        },\n        \"createdOn\": 1742195093000,\n\
                    \        \"lastUpdatedOn\": 1742195093000,\n        \"createdBy\"\
                    : 75152721,\n        \"lastUpdatedBy\": 75152721,\n        \"\
                    createdOnDateTime\": \"2025-03-17T07:04:53Z\",\n        \"lastUpdatedOnDateTime\"\
                    : \"2025-03-17T07:04:53Z\",\n        \"redemptionType\": \"POINTS\"\
                    \n    }\n]"
              schema:
                oneOf:
                - type: array
                  items:
                    type: object
                    properties:
                      rewardConstraintId:
                        type: integer
                        example: 10259
                        default: 0
                      orgId:
                        type: integer
                        example: 100458
                        default: 0
                      kpi:
                        type: string
                        example: POINTS
                      constraintLevel:
                        type: string
                        example: CUSTOMER_REDEMPTION_TYPE
                      frequencyType:
                        type: string
                        example: MONTHLY
                      constraintLimitValue:
                        type: integer
                        example: 100
                        default: 0
                      isActive:
                        type: boolean
                        example: true
                        default: true
                      status:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: true
                            default: true
                          code:
                            type: integer
                            example: 0
                            default: 0
                      redemptionType:
                        type: string
                        example: 'NULL'
                - title: With sortBy=lastUpdatedOn
                  type: array
                  items:
                    type: object
                    properties:
                      rewardConstraintId:
                        type: integer
                        example: 34327
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      kpi:
                        type: string
                        example: POINTS
                      constraintLevel:
                        type: string
                        example: CUSTOMER_REDEMPTION_TYPE
                      frequencyType:
                        type: string
                        example: DAILY
                      constraintLimitValue:
                        type: integer
                        example: 15
                        default: 0
                      isActive:
                        type: boolean
                        example: true
                        default: true
                      intervalValue:
                        type: integer
                        example: 1
                        default: 0
                      status:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: true
                            default: true
                          code:
                            type: integer
                            example: 0
                            default: 0
                      createdOn:
                        type: integer
                        example: 1747374478000
                        default: 0
                      lastUpdatedOn:
                        type: integer
                        example: 1747374478000
                        default: 0
                      createdBy:
                        type: integer
                        example: 75161973
                        default: 0
                      lastUpdatedBy:
                        type: integer
                        example: 75161973
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-05-16T05:47:58Z'
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-05-16T05:47:58Z'
                      redemptionType:
                        type: string
                        example: CASH
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: https://eucrm.cc.capillarytech.com/api_gateway/rewards/core/v1/brand/constraints
        - language: curl
          code: 'curl --location ''https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/brand/constraints?orderBy=DESC&sortBy=lastUpdatedOn''
            \

            --header ''Accept: application/json'' \

            --header ''Content-Type: application/json'' \

            --header ''accept: application/json'' \

            --header ''Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg=''
            \

            --header ''Cookie: _cfuvid=uhTtxlP23uZ.hb5OlDs7wWzPVVOQ89Yv7IGmE9Z4Qm4-1747308482787-0.0.1.1-604800000;
            _cfuvid=uhTtxlP23uZ.hb5OlDs7wWzPVVOQ89Yv7IGmE9Z4Qm4-1747308482787-0.0.1.1-604800000;
            _cfuvid=0HswOUeY1hLB1ChixiPHPvEBpkBYBw.OmrLWQyfiBZ0-1747382714367-0.0.1.1-604800000'''
          name: With sortBy=lastUpdatedOn
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
