openapi: 3.1.0
info:
  title: Get Uploaded Coupons' Status
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /coupon/api/v1/upload/getUploadStatus/{couponSeriesId}:
    get:
      summary: Get Uploaded Coupons' Status
      description: Retrieves the status of a coupon upload job.
      operationId: get-uploaded-coupons-status-copy
      parameters:
      - name: couponSeriesId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample Response:
                  value: "{\n   \"success\":true,\n   \"status\":200,\n   \"result\"\
                    :{\n      \"orgId\":2345,\n      \"couponSeriesId\":253543,\n\
                    \      \"uploadJobStatuses\":[\n         {\n            \"jobId\"\
                    :93477,\n            \"uploadStatus\":\"FINISHED\",\n        \
                    \    \"createdOn\":\"1603101625000\",\n            \"updatedOn\"\
                    :\"1603101632000\",\n            \"errorFileUrl\":\"error_1619_2532342020_10_19_15_30_32\"\
                    ,\n            \"successFileUrl\":null,\n            \"uploadedFileUrl\"\
                    :\"couponCode_1603101623721_253234.csv\",\n            \"totalUploadedCount\"\
                    :3,\n            \"actualRowCount\":3,\n            \"errorCount\"\
                    :3,\n            \"uploadTableName\":\"temp_1619_20201019_153531582\"\
                    ,\n            \"uploadedFileName\":\"couponCode.csv\",\n    \
                    \        \"audienceGroupId\":0,\n            \"audienceGroupVersionId\"\
                    :0\n         }\n      ]\n   }\n}"
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                    default: true
                  status:
                    type: integer
                    example: 200
                    default: 0
                  result:
                    type: object
                    properties:
                      orgId:
                        type: integer
                        example: 2345
                        default: 0
                      couponSeriesId:
                        type: integer
                        example: 253543
                        default: 0
                      uploadJobStatuses:
                        type: array
                        items:
                          type: object
                          properties:
                            jobId:
                              type: integer
                              example: 93477
                              default: 0
                            uploadStatus:
                              type: string
                              example: FINISHED
                            createdOn:
                              type: string
                              example: '1603101625000'
                            updatedOn:
                              type: string
                              example: '1603101632000'
                            errorFileUrl:
                              type: string
                              example: error_1619_2532342020_10_19_15_30_32
                            successFileUrl: {}
                            uploadedFileUrl:
                              type: string
                              example: couponCode_1603101623721_253234.csv
                            totalUploadedCount:
                              type: integer
                              example: 3
                              default: 0
                            actualRowCount:
                              type: integer
                              example: 3
                              default: 0
                            errorCount:
                              type: integer
                              example: 3
                              default: 0
                            uploadTableName:
                              type: string
                              example: temp_1619_20201019_153531582
                            uploadedFileName:
                              type: string
                              example: couponCode.csv
                            audienceGroupId:
                              type: integer
                              example: 0
                              default: 0
                            audienceGroupVersionId:
                              type: integer
                              example: 0
                              default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl -i -X GET \nhttps://eu.intouch.capillarytech.com/coupon/api/v1/upload/getUploadStatus/253234\
            \ \n-H 'Content-Type: application/json' \n-H 'x-cap-api-oauth-token: \n\
            \neyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJDYXBpbGxhcnkiLCJleHAiOjE2MDMyNjQ4NzksImp0aSI6IlBEV0JLRXZCTFh0VUZEdnhvbkFoNFEiLCJpYXQiOjE2MDMyNjQyNzksInN1YiI6InJlZGVtcHRpb24gaW1wb3J0IGNvdXBvbnMiLCJjbGllbnRfaWQiOjEyNjEsIm9yZ19pZCI6MTYxOSwidG9rZW5fdXNlIjoidG9rZW5fYWNjZXNzIiwiY2xpZW50X2tleSI6IldUMFQzcFdpU1JOTGFvdFBrbWFiWGR3VVgiLCJkZWZhdWx0X3RpbGwiOjE1MTQ3MTEwLCJzY29wZXMiOiJbe1wicGVybWlzc2lvblwiOlwiUkVBRFdSSVRFXCIsXCJlbnRpdHlJZFwiOjEsXCJyZXNvdXJjZXNcIjpbXCIuKnYxLjEvY3VzdG9tZXIvLipcIl19LHtcInBlcm1pc3Npb25cIjpcIlJFQURXUklURVwiLFwiZW50aXR5SWRcIjoyLFwicmVzb3VyY2VzXCI6W1wiLip2MS4xL3RyYW5zYWN0aW9uLy4qXCJdfSx7XCJwZXJtaXNzaW9uXCI6XCJSRUFEV1JJVEVcIixcImVudGl0eUlkXCI6MyxcInJlc291cmNlc1wiOltcIi4qdjEuMS9wb2ludHMvLipcIl19LHtcInBlcm1pc3Npb25cIjpcIlJFQURXUklURVwiLFwiZW50aXR5SWRcIjo0LFwicmVzb3VyY2VzXCI6W1wiLipcIl19XSJ9.xZuDQbcoekA7NsRZnNYTo1eIzjMeATccbmiR9lUdTeLZjRo453GqiBhezIfafw6GBYaDkOrJcjJCRscJt2cSlUUi8jw2z1QIuJLYIS2kQ_BFvuOUuc0p3olgyEjPdRNK3gqdD9gfQSK92_o05xLSOM205nBUeFrgaFUjuU30XcxfXOe6J7e61tOMAyxH-7ESAycOO4lo78iaSWpjio33n0rW4ngJ6PwrZQxN14JIrNkOit_r8CuZtqOTwYpF7SbZY9JG1wmYu4MT08J00neUS7j-QU9cgUaJAkd8pzoi6HhaZfpIjPaf3rSvB6doWmofyhDQc0jtVZK1iQqTovSOBg'\n"
          name: Sample Request
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
