openapi: 3.1.0
info:
  title: Get reward details by ID in connected orgs
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /v1.1/user/rewards/{rewardId}:
    get:
      summary: Get reward details by ID in connected orgs
      description: ''
      operationId: get-reward-details-by-id-in-a-connected-org
      parameters:
      - name: rewardId
        in: path
        description: The unique identifier of the reward.
        schema:
          type: integer
          format: int32
        required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                With OTHER as DATA-SCOPE:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 6001,\n        \"message\": \"Reward fetched successfully\"\
                    \n    },\n    \"reward\": {\n        \"id\": 55724,\n        \"\
                    type\": \"POINTS\",\n        \"startDate\": \"2024-04-10 11:51:50\"\
                    ,\n        \"endDate\": \"2025-11-29 11:09:49\",\n        \"enabled\"\
                    : true,\n        \"priority\": 1,\n        \"intouchPoints\":\
                    \ 0,\n        \"intouchSeriesId\": null,\n        \"tier\": \"\
                    SILVER\",\n        \"group\": null,\n        \"tillId\": null,\n\
                    \        \"programId\": null,\n        \"label\": null,\n    \
                    \    \"redemptionType\": \"MILES\",\n        \"vendorId\": 138,\n\
                    \        \"vendorRedemption\": 5166,\n        \"communications\"\
                    : null,\n        \"categories\": null,\n        \"geography\"\
                    : null,\n        \"languageSpecificInfo\": [\n            {\n\
                    \                \"rewardId\": 55724,\n                \"languageCode\"\
                    : \"en\",\n                \"name\": \" INTOUCH Enabled\",\n \
                    \               \"description\": \"Description\",\n          \
                    \      \"termNConditionsId\": \"EXDR12987R\",\n              \
                    \  \"termNConditionsUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987R?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=66d511a22d270ede7df418849ee351433701390d95b57f58a808ebcc3003631c\"\
                    ,\n                \"imageId\": \"EXDR12987U\",\n            \
                    \    \"imageUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987U?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=06e6d6d0ed4d9a6ed35c470dd7b850b64e05e9d296536cb540973d4ca52567d7\"\
                    ,\n                \"thumbnailId\": \"EXDR12987T\",\n        \
                    \        \"thumbnailUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987T?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5deeab87c79a60b4b66c13a9c9f7279c05048e9a0b3e2da7c134c8c95f7f2be9\"\
                    ,\n                \"enabled\": true,\n                \"images\"\
                    : [],\n                \"videos\": [],\n                \"customFields\"\
                    : {\n                    \"047e\": \"defaultValue\",\n       \
                    \             \"fe8b\": \"defaultValue\",\n                  \
                    \  \"9c9d\": \"defaultValue\",\n                }\n          \
                    \  }\n        ],\n        \"customFields\": {\n            \"\
                    047e\": \"defaultValue\",\n            \"fe8b\": \"defaultValue\"\
                    ,\n        },\n        \"owners\": null,\n        \"supplementaryCriteriaRO\"\
                    : [],\n        \"groupName\": null,\n        \"groupRank\": null,\n\
                    \        \"rewardRank\": null,\n        \"restrictions\": null,\n\
                    \        \"rewardRevenueMeta\": [],\n        \"rewardRevenueDefaults\"\
                    : [],\n        \"paymentConfigs\": [\n            {\n        \
                    \        \"paymentMode\": \"CONV_RATIO\",\n                \"\
                    id\": 11,\n                \"conversionRatio\": 0.3300\n     \
                    \       }\n        ],\n        \"orgLevelRestrictions\": [\n \
                    \           {\n                \"isValid\": true,\n          \
                    \      \"orgId\": 4000084\n            },\n            {\n   \
                    \             \"isValid\": true,\n                \"orgId\": 4000085\n\
                    \            }\n        ]\n    }\n}"
                'Failure: With ALL as a scope':
                  value: "{\n    \"data\": null,\n    \"errors\": [\n      {\n   \
                    \     \"code\": 310141,\n        \"message\": 'Datascope 'ALL'\
                    \ is not supported for this 'API'\n      }\n      ],\n    \"warnings\"\
                    : null\n}"
            text/plain:
              examples:
                With SELF as DATA-SCOPE:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 6001,\n        \"message\": \"Reward fetched successfully\"\
                    \n    },\n    \"reward\": {\n        \"id\": 55724,\n        \"\
                    type\": \"POINTS\",\n        \"startDate\": \"2024-04-10 11:51:50\"\
                    ,\n        \"endDate\": \"2025-11-29 11:09:49\",\n        \"enabled\"\
                    : true,\n        \"priority\": 1,\n        \"intouchPoints\":\
                    \ 0,\n        \"intouchSeriesId\": null,\n        \"tier\": \"\
                    SILVER\",\n        \"group\": null,\n        \"tillId\": null,\n\
                    \        \"programId\": null,\n        \"label\": null,\n    \
                    \    \"redemptionType\": \"MILES\",\n        \"vendorId\": 138,\n\
                    \        \"vendorRedemption\": 5166,\n        \"communications\"\
                    : null,\n        \"categories\": null,\n        \"geography\"\
                    : null,\n        \"languageSpecificInfo\": [\n            {\n\
                    \                \"rewardId\": 55724,\n                \"languageCode\"\
                    : \"en\",\n                \"name\": \" INTOUCH Enabled\",\n \
                    \               \"description\": \"Description\",\n          \
                    \      \"termNConditionsId\": \"EXDR12987R\",\n              \
                    \  \"termNConditionsUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987R?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=66d511a22d270ede7df418849ee351433701390d95b57f58a808ebcc3003631c\"\
                    ,\n                \"imageId\": \"EXDR12987U\",\n            \
                    \    \"imageUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987U?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=06e6d6d0ed4d9a6ed35c470dd7b850b64e05e9d296536cb540973d4ca52567d7\"\
                    ,\n                \"thumbnailId\": \"EXDR12987T\",\n        \
                    \        \"thumbnailUrl\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/testOrg_marvel_20230822_147/EXDR12987T?X-Amz-Security-Token=FwoGZXIvYXdzEJX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDDNv4AWezGCyejIFzyLWAciB8nJGUyt8yBSJ5x%2FZlBibuImGQnnmrAMjyZA9tBEjbZFaZ7V835gOKe0U5UygwArf%2BCq3xbk273ZXUt4MWI1W9DhFAm995OGvDZbo8hOaSSvYfcKZNa0X7UWLI2tnG1gotqVFrbRAbQfJWqNv5Gm7GTn%2BQFVVP2t4izxO49H0UfuZNNLwUAxQ70FYv7sdjnvMyPO7iC9TOQf969pKOIeJOTvGxrNk%2FR5x5LA430cVikg02XBAsRKIoXiDaaN5Qldyxtaxg7uVB%2B1He%2FUCZOmlHdilXl0on8f5sAYyLaeq749YY2Vo%2BOGBMuh0jByX4fFwG5RZFWfYoBb8aYnFfWCBkjBkmp9hf%2BAskA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240416T114015Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNO2RXSZOF%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5deeab87c79a60b4b66c13a9c9f7279c05048e9a0b3e2da7c134c8c95f7f2be9\"\
                    ,\n                \"enabled\": true,\n                \"images\"\
                    : [],\n                \"videos\": [],\n                \"customFields\"\
                    : {\n                    \"047e\": \"defaultValue\",\n       \
                    \             \"fe8b\": \"defaultValue\",\n                  \
                    \  \"9c9d\": \"defaultValue\",\n                }\n          \
                    \  }\n        ],\n        \"customFields\": {\n            \"\
                    047e\": \"defaultValue\",\n            \"fe8b\": \"defaultValue\"\
                    ,\n        },\n        \"owners\": null,\n        \"supplementaryCriteriaRO\"\
                    : [],\n        \"groupName\": null,\n        \"groupRank\": null,\n\
                    \        \"rewardRank\": null,\n        \"restrictions\": null,\n\
                    \        \"rewardRevenueMeta\": [],\n        \"rewardRevenueDefaults\"\
                    : [],\n        \"paymentConfigs\": [\n            {\n        \
                    \        \"paymentMode\": \"CONV_RATIO\",\n                \"\
                    id\": 11,\n                \"conversionRatio\": 0.3300\n     \
                    \       }\n        ],\n        \"orgLevelRestrictions\": [\n \
                    \           {\n                \"isValid\": true,\n          \
                    \      \"orgId\": 4000085\n            }\n        ]\n    }\n}"
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: 'curl --location ''https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/197661''
            \

            --header ''DATA-SCOPE: SELF'' \

            --header ''CONNECTED-ORGS: [51544]'' \

            --header ''Authorization: Basic bmFtYW46Y2FiY2U5OGblahblahTM5YTY0NTY0MTY=''
            \

            --header ''Cookie: _cfuvid=xxMm_kEPa5p5wKh9ZuyskEbGrgopax35c_46Bk8Eh1k-1729140070721-0.0.1.1-604800000'''
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
