openapi: 3.1.0
info:
  title: Import earned (issued) badges of customer
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/import/customerBadges:
    post:
      summary: Import earned (issued) badges of customer
      description: ''
      operationId: import-earned-badges-of-customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
                  default: '[    {        "badgeMetaId": "654e08f2041fd452b3ef5b2e",        "customerId":
                    382442802,        "earnEventDate": 1674292011,        "earnExpiresOn":
                    1705828011    },    {        "badgeMetaId": "654e08f2041fd452b3ef5b2e",        "customerId":
                    382442802,        "earnEventDate": 1674292011,        "earnExpiresOn":
                    1705828011    } ]'
                  format: json
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response:
                  value:
                  - data:
                      badgeMetaId: 696f0fd40772ad476ecf74ac
                      customerId: 555567088
                      earnedBadgeId: 697b5f6f0772ad476ecff272
                      expiresOn: 1705828011
                      expiresOnISO: '2024-01-21T09:06:51Z'
                      requestId: d9e144be-2450-4300-892f-798f9bb68ce2_1
                      issuedId: null
                    errors: null
                    warnings: null
                  - data:
                      badgeMetaId: 697a16140772ad476ecfe51c
                      customerId: 12098734
                      earnedBadgeId: 697b5f6f0772ad476ecff275
                      expiresOn: 1667328000
                      expiresOnISO: '2022-11-01T18:40:00Z'
                      requestId: d9e144be-2450-4300-892f-798f9bb68ce2_2
                      issuedId: null
                    errors: null
                    warnings: null
                  summary: Sample response
              schema:
                type: array
                items:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 654e08f2041fd452b3ef5b2e
                        customerId:
                          type: integer
                          example: 382442802
                          default: 0
                        earnedBadgeId:
                          type: string
                          example: 6576f7d291e0b01c659ad606
                        expiresOn:
                          type: integer
                          example: 1705828011
                          default: 0
                        requestId:
                          type: string
                          example: f93f710f169c8390c41ae095986c5a50_1
                    errors: {}
                    warnings: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
