openapi: 3.1.0
info:
  title: Organisation Level Configuration for Rewards Catalog
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/brand/config:
    post:
      summary: Organisation Level Configuration for Rewards Catalog
      description: ''
      operationId: organisation-level-configuration-for-rewards-catalog
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
                  description: '{     "configKeyName": "CONF_START_OF_THE_WEEK_FOR_ORG_RESTRICTION",     "configKeyValue":
                    "SUNDAY",     "brandId": 47,     "label": "" }'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                To configure the start week for org restriction:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 3008,\n        \"message\": \"Org config updated\
                    \ successfully\"\n    },\n    \"configList\": [\n        {\n \
                    \           \"configKeyName\": \"CONF_START_OF_THE_WEEK_FOR_ORG_RESTRICTION\"\
                    ,\n            \"configKeyValue\": \"TUESDAY\",\n            \"\
                    brandId\": null,\n            \"label\": \"Add the start of the\
                    \ week for the org level restrictions, this will be applied to\
                    \ all org level restrictions with Week configurations\"\n    \
                    \    }\n    ]\n}"
                To Enable Reward Expiry Notification:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 3008,\n        \"message\": \"Org config updated\
                    \ successfully\"\n    },\n    \"configList\": [\n        {\n \
                    \           \"configKeyName\": \"CONF_SEND_REWARD_EXPIRY_NOTIFICATION_ENABLED\"\
                    ,\n            \"configKeyValue\": \"true\",\n            \"brandId\"\
                    : 1,\n            \"label\": \"Key to enable or disable the expiry\
                    \ notification for rewards. If enabled, the system will send expiry\
                    \ notification for rewards after setting the NUMBER_OF_DAYS_BEFORE_EXPIRY.\"\
                    \n        }\n    ]\n}"
                To set Reward Expiry TIme:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 3008,\n        \"message\": \"Org config updated\
                    \ successfully\"\n    },\n    \"configList\": [\n        {\n \
                    \           \"configKeyName\": \"CONF_SEND_EXPIRY_NOTIFICATION_FOR_REWARD_TIME\"\
                    ,\n            \"configKeyValue\": \"16:00\",\n            \"\
                    brandId\": 1,\n            \"label\": \"Key to set the time of\
                    \ the day to send the expiry notification for rewards.\"\n   \
                    \     }\n    ]\n}"
              schema:
                oneOf:
                - title: To configure the start week for org restriction
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 3008
                          default: 0
                        message:
                          type: string
                          example: Org config updated successfully
                    configList:
                      type: array
                      items:
                        type: object
                        properties:
                          configKeyName:
                            type: string
                            example: CONF_START_OF_THE_WEEK_FOR_ORG_RESTRICTION
                          configKeyValue:
                            type: string
                            example: TUESDAY
                          brandId: {}
                          label:
                            type: string
                            example: Add the start of the week for the org level restrictions,
                              this will be applied to all org level restrictions with
                              Week configurations
                - title: To Enable Reward Expiry Notification
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 3008
                          default: 0
                        message:
                          type: string
                          example: Org config updated successfully
                    configList:
                      type: array
                      items:
                        type: object
                        properties:
                          configKeyName:
                            type: string
                            example: CONF_SEND_REWARD_EXPIRY_NOTIFICATION_ENABLED
                          configKeyValue:
                            type: string
                            example: 'true'
                          brandId:
                            type: integer
                            example: 1
                            default: 0
                          label:
                            type: string
                            example: Key to enable or disable the expiry notification
                              for rewards. If enabled, the system will send expiry
                              notification for rewards after setting the NUMBER_OF_DAYS_BEFORE_EXPIRY.
                - title: To set Reward Expiry TIme
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 3008
                          default: 0
                        message:
                          type: string
                          example: Org config updated successfully
                    configList:
                      type: array
                      items:
                        type: object
                        properties:
                          configKeyName:
                            type: string
                            example: CONF_SEND_EXPIRY_NOTIFICATION_FOR_REWARD_TIME
                          configKeyValue:
                            type: string
                            example: '16:00'
                          brandId:
                            type: integer
                            example: 1
                            default: 0
                          label:
                            type: string
                            example: Key to set the time of the day to send the expiry
                              notification for rewards.
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": false,\n    \
                    \    \"code\": 3011,\n        \"message\": \"Brand or config key\
                    \ not found\"\n    },\n    \"configList\": [\n        {\n    \
                    \        \"configKeyName\": \"CONF_SN_ENABLED\",\n           \
                    \ \"configKeyValue\": \"true\",\n            \"brandId\": 1,\n\
                    \            \"label\": null\n        }\n    ]\n}"
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                        default: true
                      code:
                        type: integer
                        example: 3011
                        default: 0
                      message:
                        type: string
                        example: Brand or config key not found
                  configList:
                    type: array
                    items:
                      type: object
                      properties:
                        configKeyName:
                          type: string
                          example: CONF_SN_ENABLED
                        configKeyValue:
                          type: string
                          example: 'true'
                        brandId:
                          type: integer
                          example: 1
                          default: 0
                        label: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location 'https://eucrm.cc.capillarytech.com/api_gateway/rewards/core/v1/brand/config'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization:\
            \ Basic aWFtc2hpdblahblahjJlODM4ZjhlMzRkNWI1YTI5MWY=' \\\n--data '{\n\
            \    \"configKeyName\": \"CONF_SEND_REWARD_EXPIRY_NOTIFICATION_ENABLED\"\
            ,\n    \"configKeyValue\": \"true\",\n    \"brandId\": 1\n}'"
          name: Request body
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
