openapi: 3.1.0
info:
  title: Post Cart Promotions Code link API
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/promotions/{code}/link:
    post:
      summary: Post Cart Promotions Code link API
      description: This API is used to link the code of the cart promotion earned
        by the customer to the customer id.
      operationId: post-promotions-code-link-api
      parameters:
      - name: code
        in: path
        description: Code assigned to the promotion which can be used for redemption
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: integer
                  description: Unique id assigned to the customer
                  format: int32
                code:
                  type: string
                  description: Code assigned to the promotion which can be used for
                    redemption
                mode:
                  type: string
                  description: The mode of promotion
            examples:
              Request Body:
                value:
                  customerId: 1
                  code: string
                  mode: DISCOUNT
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: ''
                New Example:
                  summary: New Example
                  value:
                    data:
                      id: 68662004ee52f074465e1063
                      orgId: 100737
                      promotionId: 68661fe0ee52f074465e1062
                      promotionName: code promotion
                      code: '40807'
                      customerId: 387509610
                      active: true
                      createdOn: 1751523332753
                      validTill: 1753986599999
                      mode: DISCOUNT
                      redeemableFrom: 1751523332753
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: string
                      orgId:
                        type: integer
                        example: 0
                        default: 0
                      promotionId:
                        type: string
                        example: string
                      promotionName:
                        type: string
                        example: string
                      code:
                        type: string
                        example: string
                      customerId:
                        type: integer
                        example: 0
                        default: 0
                      active:
                        type: boolean
                        example: true
                        default: true
                      createdOn:
                        type: integer
                        example: 0
                        default: 0
                      validTill:
                        type: integer
                        example: 0
                        default: 0
                      mode:
                        type: string
                        example: DISCOUNT
                      apiError:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 0
                            default: 0
                          message:
                            type: string
                            example: string
                      redeemableFrom:
                        type: integer
                        example: 0
                        default: 0
                      restrictions:
                        type: object
                        properties:
                          additionalProp1:
                            type: array
                            items:
                              type: object
                              properties:
                                kpi:
                                  type: string
                                  example: REDEMPTION
                                maxLimit:
                                  type: integer
                                  example: 0
                                  default: 0
                                remainingRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                tempRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodStart:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodEnd:
                                  type: integer
                                  example: 0
                                  default: 0
                          additionalProp2:
                            type: array
                            items:
                              type: object
                              properties:
                                kpi:
                                  type: string
                                  example: REDEMPTION
                                maxLimit:
                                  type: integer
                                  example: 0
                                  default: 0
                                remainingRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                tempRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodStart:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodEnd:
                                  type: integer
                                  example: 0
                                  default: 0
                          additionalProp3:
                            type: array
                            items:
                              type: object
                              properties:
                                kpi:
                                  type: string
                                  example: REDEMPTION
                                maxLimit:
                                  type: integer
                                  example: 0
                                  default: 0
                                remainingRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                tempRedemption:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodStart:
                                  type: integer
                                  example: 0
                                  default: 0
                                periodEnd:
                                  type: integer
                                  example: 0
                                  default: 0
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 0
                          default: 0
                        message:
                          type: string
                          example: string
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: ''
          language: shell
          name: Generic curl
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
