openapi: 3.1.0
info:
  title: Points - Update points restriction
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/brand/constraints:
    put:
      summary: Points - Update points restriction
      description: ''
      operationId: update-points-restriction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
                  description: "[     {   \"rewardConstraintId\": 6759,         \"\
                    kpi\" :\"POINTS\",         \"constraintLevel\" : \"CUSTOMER\"\
                    ,         \"frequencyType\" : \"DAILY\",         \"intervalValue\"\
                    \ : 3,         \"constraintLimitValue\" : 8,         \"isActive\"\
                    \ : false     } ]"
            examples:
              Request Example:
                value:
                - rewardConstraintId: 6759
                  kpi: POINTS
                  constraintLevel: CUSTOMER
                  frequencyType: DAILY
                  intervalValue: 3
                  constraintLimitValue: 8
                  isActive: false
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "[\n    {\n        \"rewardConstraintId\": 6759,\n      \
                    \  \"orgId\": 50672,\n        \"kpi\": \"POINTS\",\n        \"\
                    constraintLevel\": \"CUSTOMER\",\n        \"frequencyType\": \"\
                    DAILY\",\n        \"constraintLimitValue\": 8,\n        \"isActive\"\
                    : false,\n        \"intervalValue\": 3,\n        \"status\": {\n\
                    \            \"success\": true,\n            \"code\": 0\n   \
                    \     }\n    }\n]"
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rewardConstraintId:
                      type: integer
                      example: 6759
                      default: 0
                    orgId:
                      type: integer
                      example: 50672
                      default: 0
                    kpi:
                      type: string
                      example: POINTS
                    constraintLevel:
                      type: string
                      example: CUSTOMER
                    frequencyType:
                      type: string
                      example: DAILY
                    constraintLimitValue:
                      type: integer
                      example: 8
                      default: 0
                    isActive:
                      type: boolean
                      example: false
                      default: true
                    intervalValue:
                      type: integer
                      example: 3
                      default: 0
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 0
                          default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
