openapi: 3.1.0
info:
  title: Update fulfillment status
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/fulfillmentStatus:
    put:
      summary: Update fulfillment status
      description: ''
      operationId: update-fulfillment-status
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "[\n    {\n        \"id\": 3,\n        \"orgId\": 100458,\n\
                    \        \"name\": \"Order confirmed\",\n        \"isEnabled\"\
                    : true,\n        \"lastUpdatedBy\": 75130850,\n        \"lastUpdatedOn\"\
                    : 1721724740074\n    },\n    {\n        \"id\": 4,\n        \"\
                    orgId\": 100458,\n        \"name\": \"On the way\",\n        \"\
                    isEnabled\": true,\n        \"lastUpdatedBy\": 75130850,\n   \
                    \     \"lastUpdatedOn\": 1721724740087\n    }\n]"
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 3
                      default: 0
                    orgId:
                      type: integer
                      example: 100458
                      default: 0
                    name:
                      type: string
                      example: Order confirmed
                    isEnabled:
                      type: boolean
                      example: true
                      default: true
                    lastUpdatedBy:
                      type: integer
                      example: 75130850
                      default: 0
                    lastUpdatedOn:
                      type: integer
                      example: 1721724740074
                      default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: '{}'
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: "curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/fulfillmentStatus'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization:\
            \ Basic aWFtc2hpdmFhbms6NDA1MDk0ZjQ3NjI3YjJlODM4ZjhlMzRkNWI1YTI5MWY='\
            \ \\\n--header 'Cookie: _cfuvid=ae3ZeSPXtB_sX5yqkZl8U9bLuRrPbiz8VniA2Ov6jOM-1721724554703-0.0.1.1-604800000'\
            \ \\\n--data '[\n     {\n        \"id\": 3,\n        \"name\": \"Order\
            \ confirmed\",\n        \"isEnabled\": true\n    },\n    {\n        \"\
            id\": 4,\n        \"name\": \"On the way\",\n        \"isEnabled\": true\n\
            \    }\n]'"
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
