openapi: 3.1.0
info:
  title: Update badges
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/badgeMeta:
    put:
      summary: Update badges
      description: ''
      operationId: update-badges
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
                  description: "{     \"id\": \"65608f5dfd9efd4da77df8a0\",     \"\
                    orgId\": 100606,     \"name\": \"2023GIVE\",     \"description\"\
                    : \"Badge awarded to members who donated to the NASCAR Foundation\
                    \ during the 2023 Giveathon\",     \"startOn\": 1700827200.000000000,\
                    \     \"expiresOn\": 1703178000.000000000,     \"issuedBadgeExpiry\"\
                    : {         \"expiryType\": \"NEVER\"     },     \"earnedBadgeExpiry\"\
                    : {         \"expiryType\": \"RELATIVE\",         \"relativeExpirytype\"\
                    : \"WEEKS\",         \"value\": 2     },     \"images\": [   \
                    \      {             \"name\": \"InProgress\",             \"\
                    fileSvcHandle\": \"qwer-8634-8938\",             \"url\": \"https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fimages.png?alt=media&token=4d4c91d5-ac16-41e3-a35c-d8502814b966\"\
                    ,             \"tag\": \"IN_PROGRESS\"         },         {  \
                    \           \"name\": \"Issued\",             \"fileSvcHandle\"\
                    : \"qwer-8634-8938\",             \"url\": \"https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fsuccess1.jpg?alt=media&token=66b2f0bc-9c55-4e33-a5e9-c6be96d94f2d\"\
                    ,             \"tag\": \"EARNED\"         },         {       \
                    \      \"name\": \"Unissued\",             \"fileSvcHandle\":\
                    \ \"qwer-8634-8938\",             \"url\": \"https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2F345.jpg?alt=media&token=2d2ec9b0-e3e2-419e-9710-2cd7036b22c1\"\
                    ,             \"tag\": \"UN_EARNED\"         }     ],     \"ownership\"\
                    : {         \"restrictedToOwners\": [             \"Audience_Campaigns\"\
                    \         ],         \"claims\": []     },     \"customerConstraints\"\
                    : [],     \"badgeConstraints\": [],     \"benefits\": [      \
                    \   {             \"benefitType\": \"COUPON\",             \"\
                    seriesId\": 13893         }     ],     \"tags\": [],     \"badgeGroupId\"\
                    : 10,     \"badgeRank\": 3,     \"earnType\": \"ISSUE_EARN\",\
                    \     \"issuedCount\": 1,     \"earnedCount\":1,     \"status\"\
                    : \"LIVE\",     \"createdOn\": 1700826973.505000000,     \"createdBy\"\
                    : 75097228,     \"lastUpdatedOn\": 1700826973.505000000,     \"\
                    lastUpdatedBy\": 75097228,   \t\"customFields\": {           \
                    \  \"CF1\": \"CF1\",             \"CF2 INTEGER\": \"1\",     \
                    \        \"CF3 boolean\": \"true\",             \"CF3 date\":\
                    \ \"2001-01-18 09:09:09\",             \"CF31 date\": \"\"   \
                    \  },     \"active\": true }"
                  format: json
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response:
                  value:
                    data:
                      id: 68da6e72480b423e5c687597
                      badgeNumericId: 58
                      orgId: 100737
                      name: Test badge 29/04
                      description: Make 5 transactions
                      startOn: 1759145534
                      startOnISO: '2025-09-29T11:32:14Z'
                      expiresOn: 1761823934
                      expiresOnISO: '2025-10-30T11:32:14Z'
                      earnedBadgeExpiry:
                        expiryType: RELATIVE
                        relativeExpirytype: WEEKS
                        value: 2
                      issuedBadgeExpiry:
                        expiryType: ABSOLUTE
                        type: FIXED_DATE
                        expiresOn: 1926235957
                        expiresOnISO: '2031-01-15T09:32:37Z'
                        expireWithBadgeMeta: false
                      images: []
                      ownership:
                        restrictedToOwners:
                        - Audience_Campaigns
                        - Loyalty
                        claims:
                        - ownerType: Audience_Campaigns
                          referenceId: '8378347853'
                          isActive: true
                        - ownerType: Loyalty
                          referenceId: 456565767888767868jbjhbgjkhhgk
                          isActive: true
                      customerConstraints: []
                      badgeConstraints: []
                      benefits: []
                      tags: []
                      badgeGroupId: null
                      badgeRank: 3
                      earnType: ISSUE_EARN
                      status: EXPIRED
                      createdOn: 1759145586.301
                      createdOnISO: '2025-09-29T11:33:06Z'
                      createdBy: 75176138
                      lastUpdatedOn: 1768815888.09202
                      lastUpdatedOnISO: '2026-01-19T09:44:48Z'
                      lastUpdatedBy: 75197372
                      customFields: {}
                      active: true
                    errors: []
                    warnings: []
                  summary: Sample response
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 66decf4459a5c872324b9577
                      badgeNumericId:
                        type: integer
                        example: 47
                        default: 0
                      orgId:
                        type: integer
                        example: 100458
                        default: 0
                      name:
                        type: string
                        example: Badge Issue earn40
                      description:
                        type: string
                        example: Badge With coupon benefit updated 2
                      startOn:
                        type: integer
                        example: 1725964384
                        default: 0
                      expiresOn:
                        type: integer
                        example: 1726655584
                        default: 0
                      earnedBadgeExpiry:
                        type: object
                        properties:
                          expiryType:
                            type: string
                            example: ABSOLUTE
                          type:
                            type: string
                            example: FIXED_DATE
                          expiresOn:
                            type: integer
                            example: 1726655584
                            default: 0
                          expireWithBadgeMeta:
                            type: boolean
                            example: false
                            default: true
                      issuedBadgeExpiry:
                        type: object
                        properties:
                          expiryType:
                            type: string
                            example: ABSOLUTE
                          type:
                            type: string
                            example: FIXED_DATE
                          expiresOn:
                            type: integer
                            example: 1726655584
                            default: 0
                          expireWithBadgeMeta:
                            type: boolean
                            example: false
                            default: true
                      images:
                        type: array
                      ownership:
                        type: object
                        properties:
                          restrictedToOwners:
                            type: array
                            items:
                              type: string
                              example: Loyalty
                          claims:
                            type: array
                      customerConstraints:
                        type: array
                      badgeConstraints:
                        type: array
                      benefits:
                        type: array
                      badgeGroupId: {}
                      badgeRank: {}
                      earnType:
                        type: string
                        example: EARN
                      status:
                        type: string
                        example: UPCOMING
                      createdOn:
                        type: number
                        example: 1725878084.045
                        default: 0
                      createdBy:
                        type: integer
                        example: 75130850
                        default: 0
                      lastUpdatedOn:
                        type: number
                        example: 1725878207.7501
                        default: 0
                      lastUpdatedBy:
                        type: integer
                        example: 75130850
                        default: 0
                      customFields:
                        type: object
                        properties: {}
                      active:
                        type: boolean
                        example: true
                        default: true
                  errors:
                    type: array
                  warnings:
                    type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"data\": null,\n    \"errors\": [\n        {\n \
                    \           \"code\": 400,\n            \"message\": \"JSON parse\
                    \ error: Unexpected character ('-' (code 45)): was expecting comma\
                    \ to separate Object entries; nested exception is com.fasterxml.jackson.core.JsonParseException:\
                    \ Unexpected character ('-' (code 45)): was expecting comma to\
                    \ separate Object entries\\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream);\
                    \ line: 25, column: 21]\",\n            \"reference\": null\n\
                    \        }\n    ],\n    \"warnings\": null\n}"
              schema:
                oneOf:
                - type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 723
                            default: 0
                          message:
                            type: string
                            example: Start Date cannot change once the badge is live
                          reference: {}
                    warnings: {}
                - type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 400
                            default: 0
                          message:
                            type: string
                            example: 'Invalid enum value: '''' for the field: ''ownership.restrictedToOwners.null''.
                              The value must be one of: [Loyalty, Referral_Campaigns,
                              Journeys, Audience_Campaigns, Rewards_Catalog, Goodwill_Module,
                              Milestones].'
                          reference: {}
                    warnings: {}
                - type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 400
                            default: 0
                          message:
                            type: string
                            example: "JSON parse error: Unexpected character ('-'\
                              \ (code 45)): was expecting comma to separate Object\
                              \ entries; nested exception is com.fasterxml.jackson.core.JsonParseException:\
                              \ Unexpected character ('-' (code 45)): was expecting\
                              \ comma to separate Object entries\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream);\
                              \ line: 25, column: 21]"
                          reference: {}
                    warnings: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: "curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/v1/badges/badgeMeta'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization:\
            \ Basic bWFkaMjU2YQ==' \\\n--header 'Cookie: _cfuvid=rvSJsUbK4DDG1qt9p.ywFArkr5WoVyHK8rR8vhrDpB4-1768813084882-0.0.1.1-604800000'\
            \ \\\n--data '{\n    \"id\": \"68da6e72480b423e5c687597\",\n    \"orgId\"\
            : 100737,\n    \"name\": \"Test badge 29/04\",\n    \"badgeGroupId\":\
            \ null,\n    \"badgeGroupName\": null,\n    \"badgeRank\": 3,\n    \"\
            description\": \"Make 5 transactions\",\n    \"startOn\": 1759145534.000000000,\n\
            \    \"startOnISO\": \"2025-09-29T11:32:14Z\",\n    \"expiresOn\": 1761823934.000000000,\n\
            \    \"expiresOnISO\": \"2025-10-30T11:32:14Z\",\n    \"status\": \"LIVE\"\
            ,\n    \"images\": [],\n    \"tags\": [],\n    \"issuedBadgeExpiry\":\
            \ {\n        \"type\": \"FIXED_DATE\",\n        \"expiresOn\": 1926235957,\n\
            \        \"expiryType\": \"ABSOLUTE\"\n    },\n    \"earnType\": \"ISSUE_EARN\"\
            ,\n    \"earnedBadgeExpiry\": {\n        \"expiryType\": \"RELATIVE\"\
            ,\n        \"relativeExpirytype\": \"WEEKS\",\n        \"value\": 2\n\
            \    },\n    \"ownership\": {\n        \"restrictedToOwners\": [\n   \
            \         \"Audience_Campaigns\",\n            \"Loyalty\"\n        ],\n\
            \        \"claims\": []\n    },\n    \"benefits\": [],\n    \"issuedCount\"\
            : 0,\n    \"earnedCount\": 0,\n    \"createdOn\": 1759145586.301000000,\n\
            \    \"createdOnISO\": \"2025-09-29T11:33:06Z\",\n    \"createdBy\": 75176138,\n\
            \    \"lastUpdatedOn\": 1759145586.301000000,\n    \"lastUpdatedOnISO\"\
            : \"2025-09-29T11:33:06Z\",\n    \"lastUpdatedBy\": 75176138,\n    \"\
            customFields\": {},\n    \"active\": true\n}'"
          language: shell
          name: Sample request
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
